#!/usr/bin/env node
/**
 * Pulls content from the Payload CMS (backend/) and regenerates
 * frontend/data/*.ts with the exact same exported names/types as before, so
 * no component needs to change — only where the content comes from changes.
 *
 * Run manually (`npm run sync-cms`) or on deploy, after editing content in
 * the Payload admin. If the CMS is unreachable, existing data/*.ts files are
 * left untouched — a CMS outage never breaks the storefront build.
 *
 * Usage: node scripts/sync-cms.mjs [--cms-url http://localhost:3001]
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveBadgesForDoc } from '../lib/productBadges.core.mjs'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const dataDir = path.resolve(dirname, '../data')

const cmsUrlArgIndex = process.argv.indexOf('--cms-url')
const CMS_URL =
  (cmsUrlArgIndex !== -1 && process.argv[cmsUrlArgIndex + 1]) ||
  process.env.CMS_URL ||
  'http://localhost:3001'

const GENERATED_HEADER = `// AUTO-GENERATED by \`npm run sync-cms\` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.
`

async function fetchJSON(urlPath) {
  const res = await fetch(`${CMS_URL}${urlPath}`)
  if (!res.ok) {
    throw new Error(`GET ${urlPath} -> ${res.status} ${res.statusText}`)
  }
  return res.json()
}

async function fetchAllDocs(collection, depth = 2) {
  const { docs } = await fetchJSON(`/api/${collection}?limit=500&depth=${depth}&pagination=false`)
  return docs
}

async function fetchGlobal(slug, depth = 2) {
  return fetchJSON(`/api/globals/${slug}?depth=${depth}`)
}

const mediaURL = (doc) => {
  if (!doc) return ''
  const url = typeof doc === 'string' ? '' : doc.url || ''
  return url.startsWith('http') ? url : `${CMS_URL}${url}`
}

/** Extracts a relationship's id (or `field`, when the relation is optional
 * and unset) whether depth resolved it to a full object or left it as a raw
 * id. `typeof null === 'object'` in JS, so a naive `typeof x === 'object'`
 * check crashes on an unset optional relationship — this guards against
 * that (bit us for real: a deleted product left a null dermoPicks entry). */
const relId = (value) => (value && typeof value === 'object' ? value.id : (value ?? null))
const relName = (value, field = 'name') => (value && typeof value === 'object' ? value[field] : value || '')

/** JSON.stringify, then turn `"icon": "Name"` into `"icon": ICONS.Name` so the
 * generated file holds real lucide-react component references, not strings. */
const withIconRefs = (json) => json.replace(/"icon":\s*"(\w+)"/g, '"icon": ICONS.$1')

function writeGenerated(filename, content) {
  writeFileSync(path.join(dataDir, filename), content)
  console.log(`  wrote data/${filename}`)
}

/** An editor's explicit badges win; only when none resolve to real text does
 * a single badge get computed from real signals (discount/featured/recency).
 *
 * The rule and the presets table are imported, not copied: the same module
 * backs lib/productBadges.ts and the live path in lib/storefront/products.ts,
 * so the snapshot this script writes cannot disagree with what a live page
 * renders. It is plain ESM precisely so this bare-Node script can load it. */
const resolveBadges = (p) => resolveBadgesForDoc(p)

async function syncProducts(brandsById, mediaByAlt) {
  const products = await fetchAllDocs('products')

  const img = {}
  for (const [key, doc] of mediaByAlt) img[key] = mediaURL(doc)

  const rows = products.map((p) => ({
    id: p.id,
    slug: p.slug || String(p.id),
    brand: brandsById.get(relId(p.brand)) || '',
    name: p.name,
    size: p.size || '',
    price: p.price,
    old: p.oldPrice || 0,
    cat: p.category,
    badges: resolveBadges(p),
    rating: p.rating || 5,
    reviews: p.reviews || 0,
    tint: p.tint || '#F2F2F2',
    desc: p.description || '',
  }))

  // Imported products may not have a photo yet (many supplier spreadsheets
  // ship with broken/missing image links) — fall back to an honest "photo
  // à venir" placeholder rather than an empty <Image src>, and NEVER to an
  // unrelated real editorial/lifestyle photo, which would misrepresent a
  // product shoppers haven't actually seen a picture of.
  const NO_PHOTO_PLACEHOLDER = '/assets/product-placeholder.svg'
  const imageById = new Map(
    products.map((p) => [
      p.id,
      {
        hero: mediaURL(p.image) || NO_PHOTO_PLACEHOLDER,
        gallery: (p.gallery || []).map((g) => mediaURL(g.image)).filter(Boolean),
      },
    ]),
  )

  const content = `${GENERATED_HEADER}
export type Category =
  | "Visage"
  | "Corps"
  | "Cheveux"
  | "Solaire"
  | "Baby & Mom"
  | "Maquillage"
  | "Bucco-Dentaire"
  | "Compléments alimentaires"
  | "Hygiène";

/** priority orders the pill stack — lower shows first. 1 is the automatic
 * discount badge, so a real markdown always leads. */
export type ProductBadge = { text: string; bgColor: string; textColor: string; priority: number };

export type Product = {
  id: number;
  slug: string;
  brand: string;
  name: string;
  size: string;
  price: number;
  old: number; // 0 when there is no previous price
  cat: Category;
  badges: ProductBadge[]; // [] when there is no badge
  rating: number; // 1-5
  reviews: number;
  tint: string; // background color shown behind the product image
  desc: string;
};

export const PRODUCTS: Product[] = ${JSON.stringify(rows, null, 2)};

// Mood images shared across editorial sections (not tied to one product).
// Record<string, string> rather than \`as const\` — its actual key set
// depends entirely on which media docs exist in the CMS with a matching alt
// tag, so treating it as a closed set of keys breaks the build the moment
// one of them is temporarily missing (e.g. a sparse/fresh media library).
export const IMG: Record<string, string> = ${JSON.stringify(img, null, 2)};

// Per-product hero image, keyed by product id.
const PRODUCT_IMAGE: Record<number, string> = ${JSON.stringify(
    Object.fromEntries([...imageById].map(([id, v]) => [id, v.hero])),
    null,
    2,
  )};

// Per-product gallery images (hero + alternates), keyed by product id.
const PRODUCT_GALLERY: Record<number, string[]> = ${JSON.stringify(
    Object.fromEntries([...imageById].map(([id, v]) => [id, v.gallery])),
    null,
    2,
  )};

export function getProduct(id: number): Product {
  return PRODUCTS.find((p) => p.id === id) ?? PRODUCTS[0];
}

export function productImage(id: number): string {
  return PRODUCT_IMAGE[id] ?? "/assets/product-placeholder.svg";
}

/** Hero image first, followed by this product's alternate gallery images. */
export function productGalleryImages(id: number): string[] {
  return PRODUCT_GALLERY[id]?.length ? PRODUCT_GALLERY[id] : [productImage(id)];
}

export function money(amount: number): string {
  return \`\${amount.toLocaleString("fr-FR")} MAD\`;
}

export function stars(rating: number): string {
  return "★★★★★".slice(0, rating) + "☆☆☆☆☆".slice(0, 5 - rating);
}
`
  writeGenerated('products.ts', content)
  return { imageById, productRows: rows }
}

async function syncServices() {
  const services = await fetchAllDocs('services', 1)

  const rows = services.map((s) => ({
    id: s.id,
    img: mediaURL(s.image),
    title: s.title,
    sub: s.subtitle || '',
    price: s.price || 0,
    duration: s.duration || '',
    expert: s.expert || '',
    bg: s.bg || '#F2F2F2',
    icon: s.icon,
    desc: s.description || '',
    benefits: (s.benefits || []).map((b) => b.text),
    steps: (s.steps || []).map((step, i) => ({ n: String(i + 1), title: step.title, sub: step.sub || '' })),
  }))

  const content = `${GENERATED_HEADER}
import { Baby, Feather, Palette, ScanFace, Scissors, Droplet, type LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = { Baby, Feather, Palette, ScanFace, Scissors, Droplet };

export type ServiceStep = { n: string; title: string; sub: string };

export type Service = {
  id: number;
  img: string;
  title: string;
  sub: string;
  price: number; // 0 means "Offert" (free)
  duration: string;
  expert: string;
  bg: string;
  icon: LucideIcon;
  desc: string;
  benefits: string[];
  steps: ServiceStep[];
};

export const SERVICES: Service[] = ${withIconRefs(JSON.stringify(rows, null, 2))};

export function getService(id: number): Service {
  return SERVICES.find((s) => s.id === id) ?? SERVICES[0];
}

export function servicePriceLabel(service: Service): string {
  if (!service.price) return "Offert";
  return \`\${service.price.toLocaleString("fr-FR")} MAD\`;
}
`
  writeGenerated('services.ts', content)
}

async function syncHome() {
  const home = await fetchGlobal('home')

  const heroSlides = (home.heroSlides || [])
    .filter((s) => s.active !== false)
    .map((s) => ({
      tag: s.tag || '',
      title: s.title,
      sub: s.sub || '',
      cta: s.cta,
      ctaUrl: s.ctaUrl || '/catalogue',
      secondaryCta: s.secondaryCta || '',
      secondaryCtaUrl: s.secondaryCtaUrl || '',
      align: s.align || 'right',
      overlay: s.overlay !== false,
      bg: s.bg || '',
      img: mediaURL(s.image),
      mobileImg: mediaURL(s.mobileImage),
    }))

  const promotionsGrid = {
    title: home.promotionsGrid?.title || 'Les offres du moment',
    subtitle: home.promotionsGrid?.subtitle || '',
    limit: home.promotionsGrid?.limit || 8,
  }

  const rails = (home.rails || []).map((r) => ({
    key: r.key,
    eyebrow: r.eyebrow || '',
    title: r.title,
    subtitle: r.subtitle || '',
    // Rail copy (title/eyebrow) and *which* products to show are synced
    // content, same as everything else on this page — but the products
    // themselves are resolved live against Payload on every storefront
    // request (see lib/storefront/products.ts), never baked in here, so
    // price/stock/image edits show up without re-running this script.
    productSource: r.productSource || 'manual',
    productIds: (r.products || []).map(relId).filter((id) => id !== null),
    category: r.category || '',
    brandFilterId: relId(r.brandFilter),
    limit: r.limit || 8,
    sortOrder: r.sortOrder || 'newest',
    ctaLabel: r.ctaLabel || 'Voir tout',
    ctaUrl: r.ctaUrl || '/catalogue',
    badgeStyle: r.badgeStyle || 'none',
    ...(r.editorialImage ? { editorial: { image: mediaURL(r.editorialImage) } } : {}),
  }))

  const brandsFeatured = (home.brandsFeatured || [])
    .filter((b) => b.brand)
    .map((b) => ({
      name: relName(b.brand),
      slug: relName(b.brand, 'slug'),
      phrase: b.phrase || '',
      img: mediaURL(b.image),
      ctaLabel: b.ctaLabel || 'Découvrir la marque',
    }))

  const ctaTile = (t) => ({ eyebrow: t.eyebrow || '', title: t.title, bg: t.bg || '', img: mediaURL(t.image) })
  const ctaPair1 = (home.ctaPair1 || []).map(ctaTile)
  const ctaPair2 = (home.ctaPair2 || []).map(ctaTile)

  // A dermoPick whose product was since deleted resolves to a null id
  // (see backend/src/globals/Home.ts's note on why that field isn't
  // DB-required) — drop it rather than shipping a dangling reference.
  const dermoPicks = (home.dermoPicks || [])
    .map((d) => ({ id: relId(d.product), actif: d.actif, claim: d.claim }))
    .filter((d) => d.id !== null)

  const dermoCornerCopy = {
    eyebrow: home.dermoCornerCopy?.eyebrow || 'Dermo corner',
    title: home.dermoCornerCopy?.title || 'La sélection dermatologique du moment',
    subtitle: home.dermoCornerCopy?.subtitle || '',
    ctaLabel: home.dermoCornerCopy?.ctaLabel || 'Voir le rayon dermo',
    ctaUrl: home.dermoCornerCopy?.ctaUrl || '/catalogue',
    picksTitle: home.dermoCornerCopy?.picksTitle || 'Nos soins dermo favoris',
    img: mediaURL(home.dermoCornerCopy?.image),
    autoplay: home.dermoCornerCopy?.autoplay !== false,
    autoplaySpeedMs: home.dermoCornerCopy?.autoplaySpeedMs || 4500,
  }

  const campaignProductIds = (home.campaignProducts || []).map(relId).filter((id) => id !== null)

  const imageCarouselProductIds = (home.imageCarouselProducts || []).map(relId).filter((id) => id !== null)

  const imageCarouselCopy = {
    eyebrow: home.imageCarouselCopy?.eyebrow || 'Sélection',
    title: home.imageCarouselCopy?.title || 'Nos incontournables du moment',
    subtitle: home.imageCarouselCopy?.subtitle || '',
    ctaLabel: home.imageCarouselCopy?.ctaLabel || 'Voir la sélection',
    ctaUrl: home.imageCarouselCopy?.ctaUrl || '/catalogue',
    picksTitle: home.imageCarouselCopy?.picksTitle || 'Notre sélection',
    img: mediaURL(home.imageCarouselCopy?.image),
  }

  const summerEditCopy = {
    eyebrow: home.summerEditCopy?.eyebrow || '01 / Summer Edit',
    year: home.summerEditCopy?.year || '',
    title: home.summerEditCopy?.title || "L'été commence",
    titleAccent: home.summerEditCopy?.titleAccent || 'par la peau',
    description: home.summerEditCopy?.description || '',
    ctaLabel: home.summerEditCopy?.ctaLabel || 'Découvrir la sélection',
    ctaUrl: home.summerEditCopy?.ctaUrl || '/catalogue',
    img: mediaURL(home.summerEditCopy?.heroImage),
    imgMobile: mediaURL(home.summerEditCopy?.heroImageMobile),
    imagePosition: home.summerEditCopy?.imagePosition || 'right',
    imageScale: home.summerEditCopy?.imageScale || 1.06,
    overlay: home.summerEditCopy?.overlay === true,
    highlights: (home.summerEditCopy?.highlights || []).map((h) => ({ icon: h.icon, label: h.label })),
    carousel: {
      autoplay: home.summerEditCopy?.carousel?.autoplay !== false,
      autoplaySpeedMs: home.summerEditCopy?.carousel?.autoplaySpeedMs || 5000,
      showCounter: home.summerEditCopy?.carousel?.showCounter !== false,
      showProgress: home.summerEditCopy?.carousel?.showProgress !== false,
    },
    animation: {
      enableReveal: home.summerEditCopy?.animation?.enableReveal !== false,
      enableParallax: home.summerEditCopy?.animation?.enableParallax !== false,
      staggerProducts: home.summerEditCopy?.animation?.staggerProducts !== false,
      speed: home.summerEditCopy?.animation?.speed || 'normal',
    },
    colors: {
      background: home.summerEditCopy?.colors?.background || '#F7EEE5',
      text: home.summerEditCopy?.colors?.text || '#373020',
      accent: home.summerEditCopy?.colors?.accent || '#6D28D9',
      cta: home.summerEditCopy?.colors?.cta || '#6D28D9',
    },
    fullWidth: home.summerEditCopy?.fullWidth === true,
  }

  const summerEditActs = (home.summerEditActs || []).map((a) => ({
    eyebrow: a.eyebrow || '',
    title: a.title || '',
    description: a.description || '',
    productIds: (a.products || []).map(relId).filter((id) => id !== null).slice(0, 4),
  }))

  const coffretsCopy = {
    eyebrow: home.coffretsCopy?.eyebrow || 'Idées cadeaux',
    title: home.coffretsCopy?.title || 'Coffrets & cadeaux',
    subtitle: home.coffretsCopy?.subtitle || '',
    ctaLabel: home.coffretsCopy?.ctaLabel || 'Tous les coffrets',
    ctaUrl: home.coffretsCopy?.ctaUrl || '/collections',
    layout: home.coffretsCopy?.layout || 'carousel',
    visibleDesktop: home.coffretsCopy?.visibleDesktop || 3,
    visibleMobile: home.coffretsCopy?.visibleMobile || 1,
  }

  // Cards toggled off ("active: false") stay in the CMS array so the
  // builder can re-enable them later, but never ship to the live site.
  const coffrets = (home.coffrets || [])
    .filter((c) => c.active !== false)
    .map((c) => ({
      tag: c.tag || '',
      title: c.title,
      sub: c.sub || '',
      price: c.price,
      ...(c.priceFrom ? { priceFrom: true } : {}),
      img: mediaURL(c.image),
      ctaLabel: c.ctaLabel || 'Offrir',
      ctaUrl: c.ctaUrl || '/catalogue',
      toast: c.toast || '',
    }))

  // Posts themselves are NOT synced here — they come live from the
  // instagram-posts collection (see lib/storefront/instagram.ts), synced
  // separately from the real @paradhiver account. This is only the
  // surrounding copy/behavior config.
  const instagramSection = {
    ctaText: home.instagram?.ctaText || 'Nous suivre',
    ctaUrl: home.instagram?.ctaUrl || 'https://www.instagram.com/paradhiver/',
    postCount: home.instagram?.postCount || 6,
    show: home.instagram?.show !== false,
    subtitle: home.instagram?.subtitle || '',
    title: home.instagram?.title || '',
    username: home.instagram?.username || 'paradhiver',
  }

  const brands = (home.brands || []).map((b) => relName(b)).filter(Boolean)

  const sections = (home.sections || []).map((s) => ({ key: s.key, visible: s.visible !== false }))

  const campaignCopy = {
    eyebrow: home.campaignCopy?.eyebrow || '',
    title: home.campaignCopy?.title || '',
    description: home.campaignCopy?.description || '',
    ctaLabel: home.campaignCopy?.ctaLabel || '',
    ctaUrl: home.campaignCopy?.ctaUrl || '/catalogue',
    railTitle: home.campaignCopy?.railTitle || '',
    img: mediaURL(home.campaignCopy?.image),
  }

  const marketingBanners = (home.marketingBanners || []).map((b) => ({
    campaign: b.campaign || '',
    imageMode: b.imageMode || 'overlay',
    eyebrow: b.eyebrow || '',
    title: b.title || '',
    description: b.description || '',
    ctaLabel: b.ctaLabel || '',
    ctaUrl: b.ctaUrl || '/catalogue',
    badgeLabel: b.badgeLabel || '',
    active: b.active !== false,
    startDate: b.startDate || '',
    endDate: b.endDate || '',
    img: mediaURL(b.image),
    imgMobile: mediaURL(b.imageMobile),
  }))

  const newsletterSection = {
    title: home.newsletterSection?.title || '',
    subtitle: home.newsletterSection?.subtitle || '',
    placeholder: home.newsletterSection?.placeholder || '',
    buttonLabel: home.newsletterSection?.buttonLabel || '',
    successMessage: home.newsletterSection?.successMessage || '',
    logoEnabled: home.newsletterSection?.logoEnabled !== false,
    logoSize: home.newsletterSection?.logoSize || 76,
    logoPosition: home.newsletterSection?.logoPosition || 'left',
    backgroundColor: home.newsletterSection?.backgroundColor || '#5E4074',
    textColor: home.newsletterSection?.textColor || '#FFFFFF',
    ctaColor: home.newsletterSection?.ctaColor || '#008AA5',
    borderRadius: typeof home.newsletterSection?.borderRadius === 'number' ? home.newsletterSection.borderRadius : 26,
    particlesEnabled: home.newsletterSection?.particlesEnabled !== false,
    particlesOpacity: typeof home.newsletterSection?.particlesOpacity === 'number' ? home.newsletterSection.particlesOpacity : 0.18,
  }

  const servicesTeaser = (home.servicesTeaser || []).map((s) => ({
    title: s.title,
    sub: s.sub || '',
    cta: s.cta || '',
    href: s.href || '/services',
    icon: s.icon,
  }))

  const trustBadges = (home.trustBadges || []).map((b) => ({ title: b.title, sub: b.sub || '', icon: b.icon }))
  const reviewBars = (home.reviewBars || []).map((r) => ({ n: r.n, pct: r.pct }))
  const sampleReviews = (home.sampleReviews || []).map((r) => ({
    name: r.name,
    date: r.date,
    stars: r.stars,
    text: r.text,
  }))

  const content = `${GENERATED_HEADER}
import { BadgeCheck, Droplet, Gift, Headset, Heart, Leaf, LifeBuoy, MessageCircleQuestion, ScanLine, ShieldCheck, Sparkles, Sun, Truck, type LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = { BadgeCheck, Droplet, Gift, Headset, Heart, Leaf, LifeBuoy, MessageCircleQuestion, ScanLine, ShieldCheck, Sparkles, Sun, Truck };

export type HeroSlide = {
  tag: string;
  title: string;
  sub: string;
  cta: string;
  ctaUrl: string;
  secondaryCta: string;
  secondaryCtaUrl: string;
  align: "left" | "right";
  overlay: boolean;
  bg: string;
  img: string;
  mobileImg: string;
};

export const HERO_SLIDES: HeroSlide[] = ${JSON.stringify(heroSlides, null, 2)};

export type RailProductSource = "manual" | "latest" | "featured" | "bestSelling" | "category" | "brand" | "promotion";
export type RailSortOrder = "newest" | "price-asc" | "price-desc" | "name-asc" | "rating-desc";

export type RailBadgeStyle = "none" | "new" | "rank" | "team";

export type RailDef = {
  key: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  /** How lib/storefront/products.ts resolves this rail's actual products — always live, never baked in here. */
  productSource: RailProductSource;
  productIds: number[];
  category: string;
  brandFilterId: number | null;
  limit: number;
  sortOrder: RailSortOrder;
  ctaLabel: string;
  ctaUrl: string;
  badgeStyle: RailBadgeStyle;
  editorial?: { image: string };
};

export type BrandFeatured = { name: string; slug: string; phrase: string; img: string; ctaLabel: string };

export const RAILS: RailDef[] = ${JSON.stringify(rails, null, 2)};

export const BRANDS_FEATURED: BrandFeatured[] = ${JSON.stringify(brandsFeatured, null, 2)};

export const CTA_PAIR_1 = ${JSON.stringify(ctaPair1, null, 2)};

export const CTA_PAIR_2 = ${JSON.stringify(ctaPair2, null, 2)};

export const DERMO_PICKS: { id: number; actif: string; claim: string }[] = ${JSON.stringify(dermoPicks, null, 2)};

export const DERMO_CORNER_COPY = ${JSON.stringify(dermoCornerCopy, null, 2)};

export const CAMPAIGN_PRODUCT_IDS = ${JSON.stringify(campaignProductIds, null, 2)};

export const IMAGE_CAROUSEL_PRODUCT_IDS = ${JSON.stringify(imageCarouselProductIds, null, 2)};

export const IMAGE_CAROUSEL_COPY = ${JSON.stringify(imageCarouselCopy, null, 2)};

// \`highlights[].icon\` stays a plain string name (not a resolved
// lucide-react component) even though this generated file otherwise turns
// "icon": "Name" into a real component reference elsewhere — SUMMER_EDIT_COPY
// can flow through app/(site)/page.tsx (a Server Component) as a prop into
// SummerEdit (a Client Component) during preview, and a component/function
// value can't cross that boundary. SummerEdit.tsx resolves the name itself.
export type SummerEditHighlight = { icon: string; label: string };
export type SummerEditCopy = {
  eyebrow: string;
  year: string;
  title: string;
  titleAccent: string;
  description: string;
  ctaLabel: string;
  ctaUrl: string;
  img: string;
  imgMobile: string;
  imagePosition: "left" | "right";
  imageScale: number;
  overlay: boolean;
  highlights: SummerEditHighlight[];
  carousel: { autoplay: boolean; autoplaySpeedMs: number; showCounter: boolean; showProgress: boolean };
  animation: { enableReveal: boolean; enableParallax: boolean; staggerProducts: boolean; speed: "slow" | "normal" | "fast" };
  colors: { background: string; text: string; accent: string; cta: string };
  fullWidth: boolean;
};
export type SummerEditAct = { eyebrow: string; title: string; description: string; productIds: number[] };

export const SUMMER_EDIT_COPY: SummerEditCopy = ${JSON.stringify(summerEditCopy, null, 2)};

export const SUMMER_EDIT_ACTS: SummerEditAct[] = ${JSON.stringify(summerEditActs, null, 2)};

export const TABS = ["Tous", "Visage", "Corps", "Cheveux"] as const;

export const PROMOTIONS_GRID = ${JSON.stringify(promotionsGrid, null, 2)};

export type TrustBadge = { title: string; sub: string; icon: LucideIcon };
export const TRUST_BADGES: TrustBadge[] = ${withIconRefs(JSON.stringify(trustBadges, null, 2))};

export const COFFRETS_COPY = ${JSON.stringify(coffretsCopy, null, 2)};

// Explicit type (rather than inferring from the const, as elsewhere in this
// file) because an empty CMS result would otherwise infer COFFRETS as
// never[], breaking every consumer that reads (typeof COFFRETS)[number].
export type Coffret = { tag: string; title: string; sub: string; price: number; priceFrom?: boolean; img: string; ctaLabel: string; ctaUrl: string; toast: string };

export const COFFRETS: Coffret[] = ${JSON.stringify(coffrets, null, 2)};

export const INSTAGRAM_SECTION = ${JSON.stringify(instagramSection, null, 2)};

export const BRANDS: string[] = ${JSON.stringify(brands, null, 2)};

export type ReviewBar = { n: string; pct: number };
export const REVIEW_BARS: ReviewBar[] = ${JSON.stringify(reviewBars, null, 2)};

export type SampleReview = { name: string; date: string; stars: number; text: string };
export const SAMPLE_REVIEWS: SampleReview[] = ${JSON.stringify(sampleReviews, null, 2)};

export const FREE_SHIPPING_THRESHOLD = ${home.freeShippingThreshold ?? 399};

export type SectionKey =
  | "hero"
  | "marketingBanner"
  | "ctaPair1"
  | "summerEdit"
  | "promotionsGrid"
  | "services"
  | "coffrets"
  | "campaign"
  | "imageCarousel"
  | "dermoCorner"
  | "brandsFeatured"
  | "brandsMarquee"
  | "ctaPair2"
  | "instagram"
  | "newsletter"
  | "trustBar";

/** Either a fixed section key, or "rail:<railKey>" addressing one specific
 * entry in RAILS — each rail is independently orderable/hideable, not
 * grouped under one shared "rails" slot. */
export type SectionEntryKey = SectionKey | \`rail:\${string}\`;

export const SECTION_ORDER: { key: SectionEntryKey; visible: boolean }[] = ${JSON.stringify(sections, null, 2)};

export const CAMPAIGN_COPY = ${JSON.stringify(campaignCopy, null, 2)};

export const MARKETING_BANNERS = ${JSON.stringify(marketingBanners, null, 2)};

export const NEWSLETTER_COPY = ${JSON.stringify(newsletterSection, null, 2)};

export const SERVICES_TEASER = ${withIconRefs(JSON.stringify(servicesTeaser, null, 2))};
`
  return content
}

async function syncCollectionsPage() {
  const page = await fetchGlobal('collections-page', 1)
  const cards = (page.cards || []).map((c) => ({
    title: c.title,
    sub: c.sub || '',
    count: c.count || '',
    img: mediaURL(c.image),
  }))
  return cards
}

async function syncCataloguePage() {
  const page = await fetchGlobal('catalogue-page')

  const tagToCategory = Object.fromEntries(
    (page.tagToCategory || []).map((t) => [t.tag, t.category || '']),
  )
  const catalogueBrands = (page.brands || []).map((b) => relName(b)).filter(Boolean)
  const quickFilters = (page.quickFilters || []).map((f) => f.label)

  const content = `${GENERATED_HEADER}
import { Droplets, ListChecks, Sparkles, Star, type LucideIcon } from "lucide-react";
import type { Category } from "./products";

const ICONS: Record<string, LucideIcon> = { Droplets, ListChecks, Sparkles, Star };

/** Maps a clickable tag label (from "needs" cards, brand pills, or SEO chips)
 * to the product category it filters by. An empty string means the tag is
 * shown as an active chip but doesn't narrow the results. */
export const TAG_TO_CATEGORY: Record<string, Category | ""> = ${JSON.stringify(tagToCategory, null, 2)};

export const CATALOGUE_BRANDS: string[] = ${JSON.stringify(catalogueBrands, null, 2)};

export const QUICK_FILTERS: string[] = ${JSON.stringify(quickFilters, null, 2)};

export const FEATURED_TILE = {
  title: ${JSON.stringify(page.featuredTile?.title || '')},
  sub: ${JSON.stringify(page.featuredTile?.sub || '')},
  img: ${JSON.stringify(mediaURL(page.featuredTile?.image))},
};

// Explicit types (rather than inferring from the const) because an empty CMS
// result would otherwise infer these as never[], breaking every consumer.
export type EditorialTile = { title: string; sub: string; img: string };
export type NeedCard = { title: string; sub: string; icon: LucideIcon };

export const EDITORIAL_TILES: EditorialTile[] = ${JSON.stringify(
    (page.editorialTiles || []).map((t) => ({ title: t.title, sub: t.sub || '', img: mediaURL(t.image) })),
    null,
    2,
  )};

export const NEEDS: NeedCard[] = ${withIconRefs(
    JSON.stringify(
      (page.needs || []).map((n) => ({ title: n.title, sub: n.sub || '', icon: n.icon })),
      null,
      2,
    ),
  )};

export const SEO_LINK_GROUPS = [
  {
    title: "Sous-catégories",
    items: ${JSON.stringify(Object.keys(tagToCategory).slice(0, 8))},
  },
  {
    title: "Par besoin",
    items: ${JSON.stringify(Object.keys(tagToCategory).slice(8, 16))},
  },
  {
    title: "Marques",
    items: CATALOGUE_BRANDS,
  },
];

export const GUIDE = {
  eyebrow: ${JSON.stringify(page.guide?.eyebrow || '')},
  title: ${JSON.stringify(page.guide?.title || '')},
  body: ${JSON.stringify(page.guide?.body || '')},
  cta: ${JSON.stringify(page.guide?.cta || '')},
  img: ${JSON.stringify(mediaURL(page.guide?.image))},
};

export const SEO_INTRO = {
  eyebrow: ${JSON.stringify(page.seoIntro?.eyebrow || '')},
  title: ${JSON.stringify(page.seoIntro?.title || '')},
  paragraphs: ${JSON.stringify((page.seoIntro?.paragraphs || []).map((p) => p.text))},
};
`
  return content
}

async function syncStores() {
  const docs = await fetchAllDocs('stores', 0)
  const stores = docs
    .slice()
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0))
    .map((s) => ({
      address: s.address,
      email: s.email || '',
      hours: (s.hours || []).map((h) => ({ days: h.days, hours: h.hours })),
      mapUrl: s.mapUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}`,
      name: s.name,
      phone: s.phone || '',
    }))

  const content = `${GENERATED_HEADER}
export type StoreHours = { days: string; hours: string };

export type Store = {
  name: string;
  address: string;
  phone: string;
  email: string;
  hours: StoreHours[];
  mapUrl: string;
};

export const STORES: Store[] = ${JSON.stringify(stores, null, 2)};
`
  writeGenerated('stores.ts', content)
}

async function syncSiteChrome() {
  const chrome = await fetchGlobal('site-chrome', 1)

  const topBar = {
    enabled: chrome.topBar?.enabled !== false,
    messages: (chrome.topBar?.messages || []).filter((m) => m.active !== false).map((m) => m.text),
    marqueeSpeedSec: chrome.topBar?.marqueeSpeedSec || 34,
    mobileMessage: chrome.topBar?.mobileMessage || 'Livraison offerte dès 399 MAD',
  }

  const logo = {
    img: mediaURL(chrome.logo?.image) || '/assets/logo.png',
    wordmark: chrome.logo?.wordmark || "PARA D'HIVER",
    href: chrome.logo?.href || '/',
  }

  const headerSearch = {
    enabled: chrome.headerSearch?.enabled !== false,
    placeholder: chrome.headerSearch?.placeholder || 'Rechercher un produit, une marque…',
  }

  const headerActions = (chrome.headerActions || [])
    .filter((a) => a.visible !== false)
    .map((a) => ({ key: a.key, label: a.label, icon: a.icon, href: a.href || '' }))

  const footerColumns = (chrome.footerColumns || [])
    .filter((c) => c.visible !== false)
    .map((c) => ({
      title: c.title,
      links: (c.links || []).filter((l) => l.visible !== false).map((l) => ({ label: l.label, href: l.href })),
    }))

  const content = `${GENERATED_HEADER}
// Global chrome (Top Bar, Header, Footer) shown on every route. Source: the
// "site-chrome" Payload global, edited from the Storefront Builder's
// "Global" tab (/dashboard/storefront) — one edit here reaches every page.
//
// \`icon\` stays a plain string name (not a resolved lucide-react component)
// even though this file otherwise turns "icon": "Name" into a real
// component reference elsewhere (see withIconRefs) — HEADER_ACTIONS can flow
// through app/(site)/layout.tsx (a Server Component) as a prop into Header
// (a Client Component) during preview, and a component/function value
// can't cross that boundary. Header.tsx resolves the name to a component
// itself.

export type TopBarConfig = { enabled: boolean; messages: string[]; marqueeSpeedSec: number; mobileMessage: string };
export type Logo = { img: string; wordmark: string; href: string };
export type HeaderSearchConfig = { enabled: boolean; placeholder: string };
export type HeaderAction = { key: string; label: string; icon: string; href: string };
export type FooterLink = { label: string; href: string };
export type FooterColumn = { title: string; links: FooterLink[] };

export const TOPBAR_CONFIG: TopBarConfig = ${JSON.stringify(topBar, null, 2)};

export const LOGO: Logo = ${JSON.stringify(logo, null, 2)};

export const HEADER_SEARCH: HeaderSearchConfig = ${JSON.stringify(headerSearch, null, 2)};

export const HEADER_ACTIONS: HeaderAction[] = ${JSON.stringify(headerActions, null, 2)};

export const FOOTER_COLUMNS: FooterColumn[] = ${JSON.stringify(footerColumns, null, 2)};
`
  writeGenerated('siteChrome.ts', content)
}

async function syncTheme() {
  const theme = await fetchGlobal('theme', 0)

  const resolved = {
    preset: theme.preset || 'parad-hiver',
    colorPrimary: theme.colorPrimary || '#5E4074',
    colorSecondary: theme.colorSecondary || '#008AA5',
    colorAccent: theme.colorAccent || '#5FBE00',
    colorSale: theme.colorSale || '#FF514D',
    colorTextPrimary: theme.colorTextPrimary || '#373020',
    colorTextMuted: theme.colorTextMuted || '#757D86',
    colorBackgroundSecondary: theme.colorBackgroundSecondary || '#F7EEE5',
    buttonBg: theme.buttonBg || '#5E4074',
    buttonText: theme.buttonText || '#FFFFFF',
    buttonHoverBg: theme.buttonHoverBg || '#432951',
    buttonHoverText: theme.buttonHoverText || '#FFFFFF',
    buttonRadius: typeof theme.buttonRadius === 'number' ? theme.buttonRadius : 999,
    buttonFontWeight: typeof theme.buttonFontWeight === 'number' ? theme.buttonFontWeight : 600,
    buttonLetterSpacing: typeof theme.buttonLetterSpacing === 'number' ? theme.buttonLetterSpacing : 0.08,
    badgeBg: theme.badgeBg || '#5E4074',
    badgeText: theme.badgeText || '#FFFFFF',
    badgeFontSize: typeof theme.badgeFontSize === 'number' ? theme.badgeFontSize : 10.5,
    badgeFontWeight: typeof theme.badgeFontWeight === 'number' ? theme.badgeFontWeight : 600,
    badgeLetterSpacing: typeof theme.badgeLetterSpacing === 'number' ? theme.badgeLetterSpacing : 0.06,
    badgeRadius: typeof theme.badgeRadius === 'number' ? theme.badgeRadius : 999,
    badgePaddingX: typeof theme.badgePaddingX === 'number' ? theme.badgePaddingX : 11,
    badgePaddingY: typeof theme.badgePaddingY === 'number' ? theme.badgePaddingY : 5,
    badgeGap: typeof theme.badgeGap === 'number' ? theme.badgeGap : 6,
  }

  const content = `${GENERATED_HEADER}
// Site-wide color theme. Source: the "theme" Payload global, edited from
// the Storefront Builder's "Apparence" tab (/dashboard/storefront).

export type Theme = {
  preset: string;
  colorPrimary: string;
  colorSecondary: string;
  colorAccent: string;
  colorSale: string;
  colorTextPrimary: string;
  colorTextMuted: string;
  colorBackgroundSecondary: string;
  buttonBg: string;
  buttonText: string;
  buttonHoverBg: string;
  buttonHoverText: string;
  buttonRadius: number;
  buttonFontWeight: number;
  buttonLetterSpacing: number;
  badgeBg: string;
  badgeText: string;
  badgeFontSize: number;
  badgeFontWeight: number;
  badgeLetterSpacing: number;
  badgeRadius: number;
  badgePaddingX: number;
  badgePaddingY: number;
  badgeGap: number;
};

export const THEME: Theme = ${JSON.stringify(resolved, null, 2)};
`
  writeGenerated('theme.ts', content)
}

// Resolves a link-like object (`{ type, category, brand, collectionRoute,
// pageRoute, customUrl }`) to a real route — never a hardcoded/fabricated
// path. `category`/`brand` arrive as resolved objects at depth>=1 (relName
// reads their real `slug`), so a renamed/re-slugged category or brand is
// reflected here automatically.
function resolveNavHref(item) {
  switch (item.type) {
    case 'category': {
      const slug = relName(item.category, 'slug')
      return slug ? `/shop/${slug}` : '/catalogue'
    }
    case 'brand': {
      const slug = relName(item.brand, 'slug')
      return slug ? `/marques/${slug}` : '/marques'
    }
    case 'collection':
      return item.collectionRoute || '/catalogue'
    case 'page':
      return item.pageRoute || '/'
    default:
      return item.customUrl || '/catalogue'
  }
}

async function syncNav() {
  const nav = await fetchGlobal('navigation', 1)
  const items = (nav.items || []).filter((i) => i.visible !== false)

  // Only emit `appearance`/`animation` when an editor actually set
  // something. An always-present object of empty strings would make every
  // nav item ship inline CSS variables that resolve to nothing.
  const cleanAppearance = (a) => {
    if (!a) return undefined
    const out = {}
    for (const key of ['color', 'hoverColor', 'activeColor', 'backgroundColor', 'fontWeight']) {
      if (a[key]) out[key] = a[key]
    }
    return Object.keys(out).length ? out : undefined
  }

  const cleanAnimation = (a) => {
    if (!a?.enabled || !a.type || a.type === 'none') return undefined
    return {
      type: a.type,
      duration: typeof a.duration === 'number' ? a.duration : 2,
      delay: typeof a.delay === 'number' ? a.delay : 0,
      iterationCount: a.iterationCount || 'infinite',
    }
  }

  const navItems = items.map((item) => ({
    href: resolveNavHref(item),
    label: item.label,
    megaKey: item.megaMenuEnabled ? item.label : undefined,
    ...(item.openInNewTab ? { openInNewTab: true } : {}),
    // A free hex pair overrides the themed palette; `color: 'custom'` is the
    // signal the renderer uses to read bgColor/textColor instead of its
    // CSS-var lookup table.
    badge: item.badgeLabel
      ? item.badgeBackgroundColor
        ? {
            label: item.badgeLabel,
            color: 'custom',
            bgColor: item.badgeBackgroundColor,
            textColor: item.badgeTextColor || '#FFFFFF',
          }
        : item.badgeColor && item.badgeColor !== 'none'
          ? { label: item.badgeLabel, color: item.badgeColor }
          : undefined
      : undefined,
    ...(cleanAppearance(item.appearance) ? { appearance: cleanAppearance(item.appearance) } : {}),
    ...(cleanAnimation(item.animation) ? { animation: cleanAnimation(item.animation) } : {}),
  }))

  const megaMenu = {}
  for (const item of items) {
    if (!item.megaMenuEnabled) continue
    const mm = item.megaMenu || {}
    megaMenu[item.label] = {
      subtitle: mm.subtitle || '',
      columns: (mm.columns || []).map((col) => ({
        title: col.title,
        links: (col.links || []).filter((l) => l.visible !== false).map((l) => ({ href: resolveNavHref(l), label: l.label })),
      })),
      promo: mm.promo?.title
        ? {
            img: mediaURL(mm.promo.image),
            title: mm.promo.title,
            description: mm.promo.description || '',
            ctaLabel: mm.promo.ctaLabel || '',
            ctaUrl: mm.promo.ctaUrl || '/catalogue',
          }
        : null,
    }
  }

  const content = `${GENERATED_HEADER}
// Primary navigation and the hover mega-menu columns shown underneath it.
// Source: the "navigation" Payload global, edited from the Storefront
// Builder's "Navigation" tab (/dashboard/storefront) — decoupled from the
// Categories collection on purpose (see backend/src/globals/Navigation.ts).
// Every href is resolved from a real category/brand relationship or a
// curated existing route — never "#" and never a blanket /catalogue
// fallback except when a relationship is genuinely unset.

/** "custom" means the editor supplied free hex values in bgColor/textColor;
 * the named colors resolve to theme CSS variables instead. */
export type NavBadge = {
  label: string;
  color: "plum" | "teal" | "sale" | "custom";
  bgColor?: string;
  textColor?: string;
};

export type NavAppearance = {
  color?: string;
  hoverColor?: string;
  activeColor?: string;
  backgroundColor?: string;
  fontWeight?: string;
};

export type NavAnimationType = "blink" | "pulse" | "shimmer" | "glow";

export type NavAnimation = {
  type: NavAnimationType;
  duration: number;
  delay: number;
  /** "infinite" or a stringified integer. */
  iterationCount: string;
};
export type MegaLink = { label: string; href: string };
export type MegaColumn = { title: string; links: MegaLink[] };
export type MegaPromo = { img: string; title: string; description: string; ctaLabel: string; ctaUrl: string };
export type MegaMenuContent = { subtitle: string; columns: MegaColumn[]; promo: MegaPromo | null };

export type NavItem = {
  label: string;
  href: string;
  /** Key into MEGA_MENU; omitted means no mega menu (e.g. Services). */
  megaKey?: string;
  badge?: NavBadge;
  openInNewTab?: boolean;
  /** Absent when the editor left every colour blank — the item then renders
   * with the theme colours exactly as it did before these fields existed. */
  appearance?: NavAppearance;
  /** Absent when disabled or set to "none". */
  animation?: NavAnimation;
};

export const NAV_ITEMS: NavItem[] = ${JSON.stringify(navItems, null, 2)};

export const MEGA_MENU: Record<string, MegaMenuContent> = ${JSON.stringify(megaMenu, null, 2)};
`
  writeGenerated('nav.ts', content)
}

async function main() {
  console.log(`Syncing content from ${CMS_URL} ...`)

  const [brandDocs, mediaDocs] = await Promise.all([fetchAllDocs('brands', 0), fetchAllDocs('media', 0)])
  const brandsById = new Map(brandDocs.map((b) => [b.id, b.name]))
  const mediaByAlt = new Map(mediaDocs.map((m) => [m.alt, m]))

  await syncProducts(brandsById, mediaByAlt)
  await syncServices()

  const homeContent = await syncHome()
  const collectionsCards = await syncCollectionsPage()
  const catalogueContent = await syncCataloguePage()

  // COLLECTIONS lives in data/home.ts in the original design; append it here
  // now that we also have the collections-page global's cards. Explicit type
  // for the same never[]-on-empty reason as Coffret above.
  const homeWithCollections = homeContent.replace(
    'export const FREE_SHIPPING_THRESHOLD',
    `export type CollectionCard = { title: string; sub: string; count: string; img: string };\n\nexport const COLLECTIONS: CollectionCard[] = ${JSON.stringify(collectionsCards, null, 2)};\n\nexport const FREE_SHIPPING_THRESHOLD`,
  )
  writeGenerated('home.ts', homeWithCollections)
  writeGenerated('catalogue.ts', catalogueContent)
  await syncNav()
  await syncSiteChrome()
  await syncTheme()
  await syncStores()

  console.log('Sync complete.')
}

main().catch((err) => {
  console.error('CMS sync failed, leaving existing data/*.ts untouched:')
  console.error(err.message)
  process.exit(1)
})
