/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    categories: Category;
    products: Product;
    services: Service;
    stores: Store;
    orders: Order;
    suppliers: Supplier;
    inventory: Inventory;
    'stock-movements': StockMovement;
    'instagram-posts': InstagramPost;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'instagram-posts': InstagramPostsSelect<false> | InstagramPostsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'collections-page': CollectionsPage;
    'catalogue-page': CataloguePage;
    'site-chrome': SiteChrome;
    theme: Theme;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'collections-page': CollectionsPageSelect<false> | CollectionsPageSelect<true>;
    'catalogue-page': CataloguePageSelect<false> | CataloguePageSelect<true>;
    'site-chrome': SiteChromeSelect<false> | SiteChromeSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Controls access to /admin and the /dashboard app. "customer" has no staff access.
   */
  roles?: ('admin' | 'manager' | 'editor' | 'sales' | 'stockManager' | 'customer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Navbar / mega-menu taxonomy. Level 0 (no parent) = navbar entries. Level 1 (parent = a level-0 category) = mega-menu columns. Level 2 (parent = a level-1 category) = items inside a column. Services is intentionally not modeled here — it stays a plain top-level nav link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Not unique on purpose: the same name (e.g. "Visage") can legitimately appear at different levels of the tree.
   */
  slug?: string | null;
  /**
   * Leave empty for a top-level navbar entry.
   */
  parent?: (number | null) | Category;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  isActive?: boolean | null;
  /**
   * Optional lucide-react icon name, e.g. "Sparkles". Rarely needed below level 0.
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  brand?: (number | null) | Brand;
  category: 'Visage' | 'Corps' | 'Cheveux' | 'Solaire' | 'Baby & Mom';
  /**
   * e.g. "400 ml", "50 ml"
   */
  size?: string | null;
  price: number;
  /**
   * Leave empty when there is no barred price.
   */
  oldPrice?: number | null;
  /**
   * Small label on the product card, e.g. "-20%", "Nouveau". Leave empty for none.
   */
  badge?: string | null;
  rating?: number | null;
  reviews?: number | null;
  /**
   * Hex background color shown behind the product image, e.g. #E7EFF3
   */
  tint?: string | null;
  description: string;
  /**
   * Imported products may not have one yet — add it here once available.
   */
  image?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sku?: string | null;
  /**
   * EAN / barcode — business key used for POS lookup and Excel import.
   */
  barcode?: string | null;
  stock?: number | null;
  reservedStock?: number | null;
  lowStockThreshold?: number | null;
  isPublished?: boolean | null;
  /**
   * Highlighted in featured/curated rails.
   */
  featured?: boolean | null;
  /**
   * No longer sold — excluded from homepage rails even if stock remains, distinct from Brouillon.
   */
  discontinued?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug?: string | null;
  subtitle?: string | null;
  description: string;
  /**
   * 0 shows as "Offert" (free) on the site.
   */
  price?: number | null;
  /**
   * e.g. "30 min"
   */
  duration?: string | null;
  /**
   * e.g. "Pharmacien", "Esthéticienne"
   */
  expert?: string | null;
  /**
   * Hex background color for this service's cards, e.g. #EFE6F3
   */
  bg?: string | null;
  icon: 'Baby' | 'Feather' | 'Palette' | 'ScanFace' | 'Scissors' | 'Droplet';
  image?: (number | null) | Media;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        title: string;
        sub?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Physical parapharmacie locations shown on the services page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  name: string;
  address: string;
  phone?: string | null;
  email?: string | null;
  /**
   * One row per day or day range, e.g. "Lun – Sam" / "9h00 – 20h00".
   */
  hours?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Maps link for "Itinéraire". Leave empty to auto-build one from the address.
   */
  mapUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  shippingAddress?: string | null;
  /**
   * Snapshotted at order time — editing a product later never changes past orders.
   */
  items: {
    product?: (number | null) | Product;
    name: string;
    price: number;
    quantity: number;
    id?: string | null;
  }[];
  subtotal: number;
  shipping?: number | null;
  total: number;
  status: 'pending' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  /**
   * e.g. "CMI" or "À la livraison"
   */
  paymentMethod?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product suppliers — auto-created by the bulk importer when a "supplier" column names one that doesn't exist yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Batch-level stock records (batch number, expiry, supplier). products.stock stays the single running total.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  /**
   * Required in practice — left DB-nullable so deleting a product never crashes this record.
   */
  product?: (number | null) | Product;
  batchNumber?: string | null;
  expiryDate?: string | null;
  supplier?: (number | null) | Supplier;
  quantity: number;
  receivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of every stock change. Read-only once created.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  /**
   * Required in practice — left DB-nullable so a later product deletion never crashes or erases this record.
   */
  product?: (number | null) | Product;
  previousStock: number;
  newStock: number;
  /**
   * newStock - previousStock, positive or negative.
   */
  delta: number;
  source: 'import' | 'manual' | 'order' | 'adjustment' | 'restock';
  /**
   * e.g. "Import CSV — 2026-08-10", "Correction manuelle", or a restock note.
   */
  reason?: string | null;
  batchNumber?: string | null;
  expiryDate?: string | null;
  supplier?: (number | null) | Supplier;
  /**
   * Optional purchase order / invoice reference for a restock.
   */
  reference?: string | null;
  /**
   * The staff member who performed this movement — empty for automated sources (import, order).
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Synced automatically from the @paradhiver Instagram account (see the /instagram-posts/sync endpoint). Editors may adjust "sortOrder" or "isPublished" to override; every other field is overwritten on the next sync.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts".
 */
export interface InstagramPost {
  id: number;
  instagramId: string;
  permalink: string;
  imageUrl: string;
  thumbnailUrl?: string | null;
  caption?: string | null;
  mediaType: 'IMAGE' | 'VIDEO' | 'CAROUSEL_ALBUM';
  timestamp: string;
  username?: string | null;
  /**
   * Set automatically: true when synced from Instagram, false when the sync no longer finds this post there (deleted on Instagram). Uncheck manually to hide a post from the storefront without deleting it.
   */
  isPublished?: boolean | null;
  /**
   * Lower shows first. Left at 0 for every post, the storefront falls back to newest-first — set a lower value on specific posts to pin them earlier. Never touched by the sync job once a post exists.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'instagram-posts';
        value: number | InstagramPost;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  order?: T;
  isActive?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  category?: T;
  size?: T;
  price?: T;
  oldPrice?: T;
  badge?: T;
  rating?: T;
  reviews?: T;
  tint?: T;
  description?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  sku?: T;
  barcode?: T;
  stock?: T;
  reservedStock?: T;
  lowStockThreshold?: T;
  isPublished?: T;
  featured?: T;
  discontinued?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  price?: T;
  duration?: T;
  expert?: T;
  bg?: T;
  icon?: T;
  image?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        sub?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  phone?: T;
  email?: T;
  hours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  mapUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?: T;
  items?:
    | T
    | {
        product?: T;
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  product?: T;
  batchNumber?: T;
  expiryDate?: T;
  supplier?: T;
  quantity?: T;
  receivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  product?: T;
  previousStock?: T;
  newStock?: T;
  delta?: T;
  source?: T;
  reason?: T;
  batchNumber?: T;
  expiryDate?: T;
  supplier?: T;
  reference?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts_select".
 */
export interface InstagramPostsSelect<T extends boolean = true> {
  instagramId?: T;
  permalink?: T;
  imageUrl?: T;
  thumbnailUrl?: T;
  caption?: T;
  mediaType?: T;
  timestamp?: T;
  username?: T;
  isPublished?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every editable block on the homepage, in the order it renders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Render order and visibility of each homepage section. Edited from the Storefront Builder (/dashboard/storefront) — reordering this array reorders the homepage. Either one of the fixed section keys, or "rail:<railKey>" addressing one specific entry in `rails` below (each rail is independently orderable, not grouped under a single "rails" slot).
   */
  sections?:
    | {
        key: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Slides shown in the top hero carousel.
   */
  heroSlides?:
    | {
        /**
         * Unchecking hides this slide without deleting it.
         */
        active?: boolean | null;
        /**
         * Eyebrow shown above the title, e.g. "Édition hiver".
         */
        tag?: string | null;
        title: string;
        sub?: string | null;
        cta: string;
        /**
         * e.g. /shop, /shop/visage, /shop/brand/vichy, /produit/162
         */
        ctaUrl?: string | null;
        /**
         * Optional second button — leave both fields empty to omit it.
         */
        secondaryCta?: string | null;
        secondaryCtaUrl?: string | null;
        align?: ('right' | 'left') | null;
        /**
         * Dark gradient scrim behind the text, for legibility over busy photos.
         */
        overlay?: boolean | null;
        /**
         * CSS gradient/color used behind the slide, e.g. linear-gradient(120deg,#2f1f3d,#5E4074 60%,#4b3563)
         */
        bg?: string | null;
        image: number | Media;
        mobileImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Two-tile CTA banner right under the hero (exactly 2 tiles).
   */
  ctaPair1?:
    | {
        eyebrow?: string | null;
        title: string;
        /**
         * Hex color, e.g. #E7EFF3
         */
        bg?: string | null;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Horizontal product rails ("Les essentiels de la saison", "Nouveautés", "Best sellers"...).
   */
  rails?:
    | {
        /**
         * Stable identifier, e.g. "saison", "nouveautes".
         */
        key: string;
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        /**
         * Where this rail's products come from, resolved live against the database on every storefront request (not baked in at content-sync time).
         */
        productSource: 'manual' | 'latest' | 'featured' | 'bestSelling' | 'category' | 'brand' | 'promotion';
        /**
         * Used when "Source" is set to Sélection manuelle.
         */
        products?: (number | Product)[] | null;
        /**
         * Used when "Source" is set to Par catégorie.
         */
        category?: ('Visage' | 'Corps' | 'Cheveux' | 'Solaire' | 'Baby & Mom') | null;
        /**
         * Required when "Source" is Par marque; an optional extra filter for any other source.
         */
        brandFilter?: (number | null) | Brand;
        /**
         * Maximum number of products to show in this rail.
         */
        limit?: number | null;
        /**
         * Ignored for Sélection manuelle (keeps pick order) and Meilleures ventes (ranked by real order quantities, falling back to "Plus récents" until real sales exist).
         */
        sortOrder?: ('newest' | 'price-asc' | 'price-desc' | 'name-asc' | 'rating-desc') | null;
        /**
         * "Voir tout" link at the top-right of the rail.
         */
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        /**
         * A small editorial accent so consecutive rails don't all look identical.
         */
        badgeStyle?: ('none' | 'new' | 'rank' | 'team') | null;
        /**
         * Legacy single-brand spotlight support — superseded by the "Marques à l'honneur" section below for new content.
         */
        editorialImage?: (number | null) | Media;
        /**
         * Deprecated: kept only so no historical data is lost. New brand spotlights belong in the "Marques à l'honneur" section (brandsFeatured) below, not here.
         */
        brandFeature?: {
          name?: string | null;
          desc?: string | null;
          /**
           * Hex color, e.g. #E7EFF3
           */
          bg?: string | null;
          image?: (number | null) | Media;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * The single, consolidated "Marques à l'honneur" carousel — replaces the old pattern of attaching a one-off brand spotlight to individual rails (which produced duplicate-looking sections).
   */
  brandsFeatured?:
    | {
        brand: number | Brand;
        /**
         * Short line under the brand name, e.g. "Dermatologie et eau thermale."
         */
        phrase?: string | null;
        image?: (number | null) | Media;
        ctaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Second two-tile CTA banner, further down the page (exactly 2 tiles).
   */
  ctaPair2?:
    | {
        eyebrow?: string | null;
        title: string;
        /**
         * Hex color, e.g. #E7EFF3
         */
        bg?: string | null;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Copy for the "Les offres du moment" section. Products themselves are always resolved live by category tab — this only controls title/subtitle/count, not a fixed list of products.
   */
  promotionsGrid?: {
    title?: string | null;
    subtitle?: string | null;
    limit?: number | null;
  };
  /**
   * Editorial header for the Dermo Corner section (the product picks below are configured separately, in dermoPicks).
   */
  dermoCornerCopy?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    /**
     * Heading for the product carousel shown below the image/text band (a separate section, not merged into one card).
     */
    picksTitle?: string | null;
    image?: (number | null) | Media;
    /**
     * Automatically scroll through the product picks below.
     */
    autoplay?: boolean | null;
    /**
     * Milliseconds between each autoplay advance. Ignored if autoplay is off.
     */
    autoplaySpeedMs?: number | null;
  };
  /**
   * "Conseil dermo" strip: an active ingredient + claim for a handful of products. Maximum 8 — extra entries are ignored on the storefront.
   */
  dermoPicks?:
    | {
        /**
         * Not required: deleting a featured product must not be blocked by this reference.
         */
        product?: (number | null) | Product;
        actif: string;
        claim: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial image + copy for the "Image + carrousel produits" section — an editorial image on the left with a product carousel beside it, distinct from Dermo Corner (which stacks image/text above its rail instead of beside it).
   */
  imageCarouselCopy?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    /**
     * Small heading shown above the product carousel, beside the image.
     */
    picksTitle?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Products shown in the carousel beside the image. Maximum 8 — extra entries are ignored on the storefront.
   */
  imageCarouselProducts?: (number | Product)[] | null;
  /**
   * Seasonal editorial campaign block — an asymmetric hero (image + oversized title) followed by up to 3 "acts", each its own small product carousel. Independent of Dermo Corner and "Nos coups de cœur".
   */
  summerEditCopy?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Second line of the title, set in the accent color — leave empty for a single-color title.
     */
    titleAccent?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    heroImage?: (number | null) | Media;
    heroImageMobile?: (number | null) | Media;
    /**
     * Background mood for the hero band.
     */
    theme?: ('cream' | 'plum') | null;
    /**
     * Up to 3 short highlights under the CTA, e.g. "Protection solaire".
     */
    highlights?:
      | {
          icon: 'Sun' | 'Droplet' | 'Leaf' | 'Sparkles' | 'ShieldCheck';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * "Actes" of the campaign (e.g. Protéger, Réparer) — each is its own compact editorial band with a small automatic product carousel. Maximum 3 acts, 4 products each.
   */
  summerEditActs?:
    | {
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        /**
         * Maximum 4 — extra entries are ignored on the storefront.
         */
        products?: (number | Product)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Editorial copy + image for the "Nos coups de cœur" block (image + product carousel, left/right on desktop).
   */
  campaignCopy?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    railTitle?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Products shown in the seasonal campaign block.
   */
  campaignProducts?: (number | Product)[] | null;
  /**
   * Heading, link and layout for the "Coffrets & cadeaux" block (GiftSetsCarousel).
   */
  coffretsCopy?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    layout?: ('carousel' | 'grid') | null;
    /**
     * Approximate number of cards visible at once on desktop (carousel layout).
     */
    visibleDesktop?: number | null;
    /**
     * Approximate number of cards visible at once on mobile (carousel layout).
     */
    visibleMobile?: number | null;
  };
  /**
   * Gift box / gift card cards, 4 to 8 recommended. Reorder by dragging.
   */
  coffrets?:
    | {
        /**
         * Uncheck to hide this card without deleting it.
         */
        active?: boolean | null;
        tag?: string | null;
        title: string;
        sub?: string | null;
        price: number;
        /**
         * Show price as "à partir de" (from), e.g. for gift cards.
         */
        priceFrom?: boolean | null;
        image: number | Media;
        ctaLabel?: string | null;
        ctaUrl?: string | null;
        /**
         * Confirmation toast text shown after adding to cart.
         */
        toast?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copy and behavior around the homepage Instagram section. The posts themselves are NOT set here — they sync automatically from the @paradhiver account into the "Instagram Posts" collection.
   */
  instagram?: {
    show?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    username?: string | null;
    /**
     * How many posts to show. 6 fits one row on desktop.
     */
    postCount?: number | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Brand logos scrolling in the marquee, in display order.
   */
  brands?: (number | Brand)[] | null;
  /**
   * Trust bar at the bottom of the page.
   */
  trustBadges?:
    | {
        title: string;
        sub?: string | null;
        icon: 'Truck' | 'ShieldCheck' | 'BadgeCheck' | 'Headset';
        id?: string | null;
      }[]
    | null;
  /**
   * Star-rating distribution bars shown on product pages.
   */
  reviewBars?:
    | {
        n: string;
        pct: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Placeholder reviews shown on product pages until real reviews exist.
   */
  sampleReviews?:
    | {
        name: string;
        date: string;
        stars: number;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * "Nos services" cards on the homepage.
   */
  servicesTeaser?:
    | {
        title: string;
        sub?: string | null;
        cta?: string | null;
        href?: string | null;
        icon:
          | 'ScanLine'
          | 'Truck'
          | 'MessageCircleQuestion'
          | 'LifeBuoy'
          | 'ShieldCheck'
          | 'BadgeCheck'
          | 'Headset'
          | 'Sparkles'
          | 'Heart'
          | 'Gift';
        id?: string | null;
      }[]
    | null;
  /**
   * Newsletter signup banner near the bottom of the homepage.
   */
  newsletterSection?: {
    title?: string | null;
    subtitle?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
  };
  freeShippingThreshold?: number | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The editorial "collections" landing page (/collections).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections-page".
 */
export interface CollectionsPage {
  id: number;
  cards?:
    | {
        title: string;
        sub?: string | null;
        /**
         * e.g. "24 produits"
         */
        count?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Filter pills, editorial blocks and SEO content on the /catalogue page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-page".
 */
export interface CataloguePage {
  id: number;
  /**
   * Pills at the top of the catalogue, e.g. "Nouveautés", "Coffrets".
   */
  quickFilters?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Maps a "besoin" tag (shown as a clickable chip) to the product category it filters by. Leave category empty for a purely illustrative tag.
   */
  tagToCategory?:
    | {
        tag: string;
        category?: ('Visage' | 'Corps' | 'Cheveux' | 'Solaire' | 'Baby & Mom') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Brands offered as a filter on the catalogue page.
   */
  brands?: (number | Brand)[] | null;
  featuredTile?: {
    title?: string | null;
    sub?: string | null;
    image?: (number | null) | Media;
  };
  editorialTiles?:
    | {
        title: string;
        sub?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * "Besoin d'un conseil ?" cards.
   */
  needs?:
    | {
        title: string;
        sub?: string | null;
        icon: 'Droplets' | 'Sparkles' | 'Star' | 'ListChecks';
        id?: string | null;
      }[]
    | null;
  guide?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
    cta?: string | null;
    image?: (number | null) | Media;
  };
  seoIntro?: {
    eyebrow?: string | null;
    title?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top bar, header and footer — shown on every page. Edited from the Storefront Builder's "Global" tab (/dashboard/storefront).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-chrome".
 */
export interface SiteChrome {
  id: number;
  /**
   * Scrolling promo ticker above the header.
   */
  topBar?: {
    enabled?: boolean | null;
    /**
     * Shown as a scrolling marquee on desktop/tablet.
     */
    messages?:
      | {
          text: string;
          /**
           * Uncheck to hide without deleting.
           */
          active?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Seconds for one full loop of the marquee — lower is faster.
     */
    marqueeSpeedSec?: number | null;
    /**
     * A moving ticker is hard to read on a phone — mobile shows this single static message instead.
     */
    mobileMessage?: string | null;
  };
  logo?: {
    /**
     * Leave empty to keep the default logo mark.
     */
    image?: (number | null) | Media;
    wordmark?: string | null;
    href?: string | null;
  };
  headerSearch?: {
    enabled?: boolean | null;
    placeholder?: string | null;
  };
  /**
   * The 4 header action icons, in display order. "Favoris" and "Panier" keep their real route/behavior — only label, icon and visibility apply to them.
   */
  headerActions?:
    | {
        key: 'services' | 'contact' | 'favoris' | 'panier';
        label: string;
        icon: 'MapPin' | 'MessageCircle' | 'Phone' | 'Mail' | 'HelpCircle' | 'Heart' | 'ShoppingBag';
        /**
         * Ignored for "Favoris" and "Panier" — their route is fixed in code, never CMS-editable.
         */
        href?: string | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer link columns, in display order. Reorder by dragging; hide a column without deleting it via "Visible".
   */
  footerColumns?:
    | {
        title: string;
        visible?: boolean | null;
        links?:
          | {
              label: string;
              href: string;
              visible?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide color theme — picking a preset or a color here re-colors the whole storefront. Edited from the Storefront Builder's "Apparence" tab (/dashboard/storefront).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Picking a preset fills the colors below; nudging a color afterwards switches this to "Personnalisé".
   */
  preset?: ('parad-hiver' | 'minimal' | 'botanical' | 'soft-beauty' | 'premium' | 'ocean' | 'custom') | null;
  /**
   * Hex color only. Overrides --pdh-plum everywhere on the storefront.
   */
  colorPrimary?: string | null;
  /**
   * Hex color only. Overrides --pdh-teal everywhere on the storefront.
   */
  colorSecondary?: string | null;
  /**
   * Hex color only. Overrides --pdh-accent everywhere on the storefront.
   */
  colorAccent?: string | null;
  /**
   * Hex color only. Overrides --pdh-sale everywhere on the storefront.
   */
  colorSale?: string | null;
  /**
   * Hex color only. Overrides --pdh-ink everywhere on the storefront.
   */
  colorTextPrimary?: string | null;
  /**
   * Hex color only. Overrides --pdh-muted everywhere on the storefront.
   */
  colorTextMuted?: string | null;
  /**
   * Hex color only. Overrides --pdh-cream everywhere on the storefront.
   */
  colorBackgroundSecondary?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        key?: T;
        visible?: T;
        id?: T;
      };
  heroSlides?:
    | T
    | {
        active?: T;
        tag?: T;
        title?: T;
        sub?: T;
        cta?: T;
        ctaUrl?: T;
        secondaryCta?: T;
        secondaryCtaUrl?: T;
        align?: T;
        overlay?: T;
        bg?: T;
        image?: T;
        mobileImage?: T;
        id?: T;
      };
  ctaPair1?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        bg?: T;
        image?: T;
        id?: T;
      };
  rails?:
    | T
    | {
        key?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        productSource?: T;
        products?: T;
        category?: T;
        brandFilter?: T;
        limit?: T;
        sortOrder?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        badgeStyle?: T;
        editorialImage?: T;
        brandFeature?:
          | T
          | {
              name?: T;
              desc?: T;
              bg?: T;
              image?: T;
            };
        id?: T;
      };
  brandsFeatured?:
    | T
    | {
        brand?: T;
        phrase?: T;
        image?: T;
        ctaLabel?: T;
        id?: T;
      };
  ctaPair2?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        bg?: T;
        image?: T;
        id?: T;
      };
  promotionsGrid?:
    | T
    | {
        title?: T;
        subtitle?: T;
        limit?: T;
      };
  dermoCornerCopy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        picksTitle?: T;
        image?: T;
        autoplay?: T;
        autoplaySpeedMs?: T;
      };
  dermoPicks?:
    | T
    | {
        product?: T;
        actif?: T;
        claim?: T;
        id?: T;
      };
  imageCarouselCopy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        picksTitle?: T;
        image?: T;
      };
  imageCarouselProducts?: T;
  summerEditCopy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleAccent?: T;
        description?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        heroImage?: T;
        heroImageMobile?: T;
        theme?: T;
        highlights?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  summerEditActs?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        products?: T;
        id?: T;
      };
  campaignCopy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        railTitle?: T;
        image?: T;
      };
  campaignProducts?: T;
  coffretsCopy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        layout?: T;
        visibleDesktop?: T;
        visibleMobile?: T;
      };
  coffrets?:
    | T
    | {
        active?: T;
        tag?: T;
        title?: T;
        sub?: T;
        price?: T;
        priceFrom?: T;
        image?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        toast?: T;
        id?: T;
      };
  instagram?:
    | T
    | {
        show?: T;
        title?: T;
        subtitle?: T;
        username?: T;
        postCount?: T;
        ctaText?: T;
        ctaUrl?: T;
      };
  brands?: T;
  trustBadges?:
    | T
    | {
        title?: T;
        sub?: T;
        icon?: T;
        id?: T;
      };
  reviewBars?:
    | T
    | {
        n?: T;
        pct?: T;
        id?: T;
      };
  sampleReviews?:
    | T
    | {
        name?: T;
        date?: T;
        stars?: T;
        text?: T;
        id?: T;
      };
  servicesTeaser?:
    | T
    | {
        title?: T;
        sub?: T;
        cta?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  newsletterSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        placeholder?: T;
        buttonLabel?: T;
        successMessage?: T;
      };
  freeShippingThreshold?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections-page_select".
 */
export interface CollectionsPageSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        title?: T;
        sub?: T;
        count?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogue-page_select".
 */
export interface CataloguePageSelect<T extends boolean = true> {
  quickFilters?:
    | T
    | {
        label?: T;
        id?: T;
      };
  tagToCategory?:
    | T
    | {
        tag?: T;
        category?: T;
        id?: T;
      };
  brands?: T;
  featuredTile?:
    | T
    | {
        title?: T;
        sub?: T;
        image?: T;
      };
  editorialTiles?:
    | T
    | {
        title?: T;
        sub?: T;
        image?: T;
        id?: T;
      };
  needs?:
    | T
    | {
        title?: T;
        sub?: T;
        icon?: T;
        id?: T;
      };
  guide?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        cta?: T;
        image?: T;
      };
  seoIntro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-chrome_select".
 */
export interface SiteChromeSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        enabled?: T;
        messages?:
          | T
          | {
              text?: T;
              active?: T;
              id?: T;
            };
        marqueeSpeedSec?: T;
        mobileMessage?: T;
      };
  logo?:
    | T
    | {
        image?: T;
        wordmark?: T;
        href?: T;
      };
  headerSearch?:
    | T
    | {
        enabled?: T;
        placeholder?: T;
      };
  headerActions?:
    | T
    | {
        key?: T;
        label?: T;
        icon?: T;
        href?: T;
        visible?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        visible?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              visible?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  preset?: T;
  colorPrimary?: T;
  colorSecondary?: T;
  colorAccent?: T;
  colorSale?: T;
  colorTextPrimary?: T;
  colorTextMuted?: T;
  colorBackgroundSecondary?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'brands'
      | 'categories'
      | 'products'
      | 'services'
      | 'stores'
      | 'orders'
      | 'suppliers'
      | 'inventory'
      | 'stock-movements'
      | 'instagram-posts'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}