"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import { CloudinaryImage } from "@/components/CloudinaryImage";
import Link from "next/link";
import { useRef } from "react";
import { Rail, type RailHandle } from "@/components/Rail";
import type { BrandFeatured } from "@/data/home";
import { routes } from "@/lib/routes";

export type BrandsFeaturedCopy = { eyebrow: string; title: string };

/** What the section says before the CMS says otherwise. Not in `data/home.ts`
 * because that file is regenerated by `sync-cms` and would lose it. */
const DEFAULT_COPY: BrandsFeaturedCopy = {
  eyebrow: "Nos partenaires",
  title: "Marques à l’honneur",
};

/** The single, consolidated "Marques à l'honneur" carousel — replaces what
 * used to be a one-off brand spotlight duplicated after individual rails. */
export function BrandsFeaturedSection({ brands, copy: copyProp }: { brands: BrandFeatured[]; copy?: BrandsFeaturedCopy }) {
  const railRef = useRef<RailHandle>(null);
  const copy = copyProp ?? DEFAULT_COPY;
  if (brands.length === 0) return null;

  return (
    <section style={{ maxWidth: "min(1280px,100%)", margin: "0 auto", padding: "var(--sec-pt,var(--sec-y)) var(--sec-pad-x) var(--sec-pb,var(--sec-y))" }}>
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 20, gap: 16, flexWrap: "wrap" }}>
        <div>
          <h2 className="sec-title">{copy.title}</h2>
        </div>
        <div style={{ display: "flex", gap: 8, flex: "none" }}>
          <button type="button" onClick={() => railRef.current?.scrollPrev()} aria-label="Marques précédentes" className="circle-btn">
            <ChevronLeft aria-hidden="true" size={16} />
          </button>
          <button type="button" onClick={() => railRef.current?.scrollNext()} aria-label="Marques suivantes" className="circle-btn">
            <ChevronRight aria-hidden="true" size={16} />
          </button>
        </div>
      </div>

      <Rail ref={railRef} ariaLabel="Marques à l'honneur" cols={{ lg: 3, md: 2.4, sm: 1.35, xl: 4 }}>
        {brands.map((b, i) => (
          <div key={b.slug || b.name} role="listitem">
            <Link
              href={b.slug ? routes.brand(b.slug) : routes.brands()}
              className="tile-hover"
              style={{
                display: "block",
                borderRadius: 20,
                overflow: "hidden",
                border: "1px solid var(--pdh-plum-tint)",
                background: "#fff",
                animation: "rise .5s both",
                animationDelay: `${i * 60}ms`,
              }}
            >
              <div style={{ position: "relative", aspectRatio: "4/3", background: "var(--pdh-sand)" }}>
                {b.img && <CloudinaryImage preset="brand" src={b.img} alt={b.name} fill sizes="300px" style={{ objectFit: "cover" }} />}
              </div>
              <div style={{ padding: "18px 20px 22px" }}>
                <div className="card-title" style={{ fontSize: 22, letterSpacing: ".04em", color: "var(--pdh-plum)" }}>{b.name}</div>
                {/* Two lines held open so a row of brand cards ends level. It
                    was a literal 40 — two lines of the 12.5/1.6 this used to
                    be — which is exactly the kind of number that goes stale
                    the moment the role it was derived from moves. Asking for
                    the arithmetic instead means it tracks --fs-deck and
                    --lh-prose without anyone remembering to. */}
                {b.phrase && (
                  <p className="sec-deck" style={{ margin: "8px 0 14px", minHeight: "calc(var(--fs-deck) * var(--lh-prose) * 2)" }}>
                    {b.phrase}
                  </p>
                )}
                <span style={{ fontSize: 11, letterSpacing: ".12em", textTransform: "uppercase", color: "var(--pdh-teal-text)" }}>{b.ctaLabel} →</span>
              </div>
            </Link>
          </div>
        ))}
      </Rail>
    </section>
  );
}
