"use client";

import { ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";
import { useRef } from "react";
import { CloudinaryImage } from "@/components/CloudinaryImage";
import { BRANDS } from "@/data/home";
import { routes } from "@/lib/routes";

export type MarqueeBrand = { name: string; slug: string; logo: string };

/**
 * The official brand counters.
 *
 * ## What this replaces
 *
 * A marquee: the brand *names*, set in Alta at half opacity, scrolling
 * sideways on a 30-second CSS animation, `aria-hidden` because there was
 * nothing in it to interact with. It read as decoration because it was
 * decoration — a moving band of grey words that said "we stock brands"
 * without saying which, and that no shopper could stop, read or click.
 *
 * A logo is doing a different job. Someone arriving cold from Instagram is
 * deciding whether this is a real parapharmacie, and a wall of marks they
 * recognise — La Roche-Posay, Vichy, Kérastase — answers that faster than any
 * sentence. So the marks are shown at a size you can actually read, they hold
 * still, and each one is a link into that brand's products.
 *
 * ## Two rows that scroll, not two rows that wrap
 *
 * `grid-auto-flow: column` with two rows fills top-then-bottom and grows
 * sideways, which is what keeps the block a fixed height whatever the brand
 * count is. Wrapping would make eight brands two rows and nine brands three,
 * and the section would change height every time an editor adds one.
 *
 * The arrows page the scroller and are hidden on touch, where the scroll
 * gesture is the affordance and a pair of buttons is just something else to
 * mis-tap. Scroll snapping keeps a page landing on a column edge rather than
 * halfway through a logo.
 *
 * ## The fallback is the point
 *
 * `logo` is empty for any brand nobody has uploaded a mark for, and this shop
 * has plenty. Those render as the brand's name in the same tile, at the same
 * size — not hidden, not a broken image, not a grey placeholder box. A shop
 * with zero logos uploaded still gets a legible, working section, which is
 * the state it is actually in today.
 */
export function BrandsMarquee({ brands }: { brands?: MarqueeBrand[] } = {}) {
  const scroller = useRef<HTMLDivElement>(null);

  // The offline snapshot is still a plain string[] — it predates logos and is
  // regenerated by sync-cms, so it is mapped here rather than migrated.
  const items: MarqueeBrand[] =
    brands && brands.length > 0 ? brands : BRANDS.map((name) => ({ name, slug: "", logo: "" }));

  if (items.length === 0) return null;

  function page(direction: 1 | -1) {
    const el = scroller.current;
    if (!el) return;
    // Most of a viewport rather than all of it: leaving a column visible on
    // the other side is what tells the reader the two views are continuous.
    el.scrollBy({ behavior: "smooth", left: direction * el.clientWidth * 0.8 });
  }

  return (
    <section
      aria-labelledby="brand-counters-title"
      style={{ maxWidth: "min(1280px,100%)", margin: "0 auto", padding: "var(--sec-pt,var(--sec-y)) var(--sec-pad-x) var(--sec-pb,var(--sec-y))" }}
    >
      <h2
        id="brand-counters-title"
        style={{
          fontFamily: "var(--font-alta)",
          fontWeight: 200,
          fontSize: "clamp(25px,3.2vw,38px)",
          lineHeight: 1.08,
          letterSpacing: "-.01em",
          margin: "0 0 26px",
          textAlign: "center",
        }}
      >
        Les boutiques officielles
      </h2>

      <div className="brand-wall">
        <button aria-label="Marques précédentes" className="brand-wall-nav" onClick={() => page(-1)} type="button">
          <ChevronLeft aria-hidden="true" size={18} strokeWidth={1.8} />
        </button>

        <div className="brand-wall-track" ref={scroller}>
          {items.map((brand, i) => {
            const inner = brand.logo ? (
              <CloudinaryImage
                alt={brand.name}
                // "limit" keeps a wordmark's own proportions: a logo stretched
                // to fill a tile is worse than a logo shown small.
                crop="limit"
                fill
                sizes="180px"
                src={brand.logo}
                style={{ objectFit: "contain" }}
              />
            ) : (
              <span className="brand-wall-name">{brand.name}</span>
            );

            // A brand with no slug has no page to open — it is still shown,
            // as a plain tile, rather than linking nowhere.
            return brand.slug ? (
              <Link className="brand-wall-cell" href={routes.brand(brand.slug)} key={brand.slug} title={brand.name}>
                {inner}
              </Link>
            ) : (
              <div className="brand-wall-cell" key={`${brand.name}-${i}`}>
                {inner}
              </div>
            );
          })}
        </div>

        <button aria-label="Marques suivantes" className="brand-wall-nav" onClick={() => page(1)} type="button">
          <ChevronRight aria-hidden="true" size={18} strokeWidth={1.8} />
        </button>
      </div>
    </section>
  );
}
