"use client";

import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CloudinaryImage } from "@/components/CloudinaryImage";
import { ProductCard } from "@/components/ProductCard";
import { PRODUCTS, productImage } from "@/data/products";
import type { LiveProduct } from "@/lib/storefront/products";

export type FeaturedPromoCopy = {
  eyebrow: string;
  title: string;
  subtitle: string;
  ctaLabel: string;
  ctaUrl: string;
  promoEyebrow: string;
  promoTitle: string;
  promoCtaLabel: string;
  promoCtaUrl: string;
  promoImage: string;
};

/** What the block says before anyone configures it. Not in `data/home.ts`:
 * that file is regenerated by `sync-cms` and would lose it. */
export const FEATURED_PROMO_DEFAULTS: FeaturedPromoCopy = {
  eyebrow: "Sélection",
  title: "Les incontournables",
  subtitle: "Choisis un par un par nos pharmaciens.",
  ctaLabel: "Voir tout",
  ctaUrl: "/catalogue",
  promoEyebrow: "Nouveautés",
  promoTitle: "Les dernières arrivées, chaque semaine",
  promoCtaLabel: "Tout parcourir",
  promoCtaUrl: "/shop/nouveautes",
  promoImage: "",
};

/**
 * A promotional tile sharing one grid with product cards.
 *
 * The banner is the first cell rather than a separate strip above the grid:
 * it is the same size and shape as the products beside it, so it reads as
 * part of the selection instead of an ad bolted on top — which is the whole
 * point of the pattern.
 *
 * Cards are the shared `ProductCard` in its `rail` variant, the one that
 * already carries the rating line, the favourite control and the badge. A
 * second, near-identical card component is how a design system starts to
 * drift.
 */
export function FeaturedWithPromo({
  copy: copyProp,
  products = [],
}: {
  copy?: Partial<FeaturedPromoCopy>;
  products?: LiveProduct[];
}) {
  const copy = { ...FEATURED_PROMO_DEFAULTS, ...copyProp };

  // The banner occupies one cell, so the grid needs products for the rest;
  // a banner on its own is not a product listing. When the CMS is
  // unreachable the snapshot stands in — photographed products first, the
  // same order the live fetcher applies — rather than the block vanishing.
  const items =
    products.length > 0
      ? products
      : PRODUCTS.filter((p) => !productImage(p.id).includes("product-placeholder")).slice(0, 3);

  if (items.length === 0) return null;

  return (
    <section style={{ maxWidth: "min(1280px,100%)", margin: "0 auto", padding: "var(--sec-pt,var(--sec-y)) var(--sec-pad-x) var(--sec-pb,var(--sec-y))" }}>
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 22, gap: 16, flexWrap: "wrap" }}>
        <div>
          <div style={{ fontFamily: "var(--font-poppins)", fontSize: 10.5, letterSpacing: ".24em", textTransform: "uppercase", color: "var(--pdh-teal-text)" }}>
            {copy.eyebrow}
          </div>
          <h2 style={{ fontFamily: "var(--font-alta)", fontWeight: 200, fontSize: "clamp(25px,3.2vw,38px)", margin: "8px 0 0", letterSpacing: "-.01em" }}>
            {copy.title}
          </h2>
          {copy.subtitle && <div style={{ fontSize: 13, opacity: 0.6, marginTop: 6, maxWidth: 620 }}>{copy.subtitle}</div>}
        </div>
        {copy.ctaLabel && (
          <Link
            href={copy.ctaUrl || "/catalogue"}
            className="link-hover"
            style={{
              flex: "none",
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              whiteSpace: "nowrap",
              fontSize: 11.5,
              letterSpacing: ".12em",
              textTransform: "uppercase",
              color: "var(--pdh-plum)",
              borderBottom: "1px solid rgba(94,64,116,.35)",
              paddingBottom: 3,
            }}
          >
            {copy.ctaLabel}
            <ArrowRight aria-hidden="true" size={14} strokeWidth={1.8} />
          </Link>
        )}
      </div>

      <div className="featured-promo-grid">
        {/* The banner. A link wrapping the whole tile, so the target is the
            card and not just the button inside it. */}
        <Link href={copy.promoCtaUrl || "/catalogue"} className="featured-promo-tile">
          {copy.promoImage && (
            <span className="featured-promo-tile-img" aria-hidden="true">
              <CloudinaryImage preset="editorial" src={copy.promoImage} alt="" fill sizes="320px" style={{ objectFit: "cover" }} />
            </span>
          )}
          <span className="featured-promo-tile-body">
            <span style={{ fontFamily: "var(--font-poppins)", fontSize: 10.5, letterSpacing: ".24em", textTransform: "uppercase", opacity: 0.75 }}>
              {copy.promoEyebrow}
            </span>
            <span style={{ fontFamily: "var(--font-alta)", fontWeight: 300, fontSize: "clamp(20px,2.2vw,26px)", lineHeight: 1.15, letterSpacing: "-.01em" }}>
              {copy.promoTitle}
            </span>
            <span className="featured-promo-cta">
              {copy.promoCtaLabel}
              <ArrowRight aria-hidden="true" size={14} strokeWidth={2} />
            </span>
          </span>
        </Link>

        {items.map((product, i) => (
          <ProductCard key={product.id} product={product} variant="rail" delayMs={i * 50} />
        ))}
      </div>
    </section>
  );
}
