// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

import { Droplets, ListChecks, Sparkles, Star, type LucideIcon } from "lucide-react";
import type { Category } from "./products";

const ICONS: Record<string, LucideIcon> = { Droplets, ListChecks, Sparkles, Star };

/** Maps a clickable tag label (from "needs" cards, brand pills, or SEO chips)
 * to the product category it filters by. An empty string means the tag is
 * shown as an active chip but doesn't narrow the results. */
export const TAG_TO_CATEGORY: Record<string, Category | ""> = {
  "Nettoyants visage": "Visage",
  "Sérums": "Visage",
  "Crèmes de jour": "Visage",
  "Contour des yeux": "Visage",
  "Baumes corps": "Corps",
  "Shampooings traitants": "Cheveux",
  "Écrans solaires": "Solaire",
  "Compléments": "Corps",
  "Peaux sensibles": "Visage",
  "Peaux sèches": "Corps",
  "Imperfections": "Visage",
  "Anti-âge": "Visage",
  "Rougeurs": "Visage",
  "Chute de cheveux": "Cheveux",
  "Grossesse": "Baby & Mom",
  "Bébé": "Baby & Mom",
  "Peau sèche & tiraillements": "Corps",
  "Routine complète": ""
};

export const CATALOGUE_BRANDS: string[] = [
  "La Roche-Posay",
  "Avène",
  "Bioderma",
  "CeraVe",
  "Vichy",
  "Uriage",
  "Nuxe",
  "Klorane",
  "Ducray",
  "Mustela"
];

export const QUICK_FILTERS: string[] = [
  "−25% sélection soin",
  "Nouveautés",
  "Meilleures ventes",
  "Exclusivités pharmacie",
  "Minis & formats voyage",
  "Coffrets",
  "Peaux sensibles",
  "Anti-âge",
  "Hydratation",
  "Bio & naturel",
  "Sans parfum",
  "Solaire SPF 50+"
];

export const FEATURED_TILE = {
  title: "Le rayon dermocosmétique",
  sub: "Les marques prescrites en pharmacie, à prix parapharmacie.",
  img: "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/dermo.png",
};

// Explicit types (rather than inferring from the const) because an empty CMS
// result would otherwise infer these as never[], breaking every consumer.
export type EditorialTile = { title: string; sub: string; img: string };
export type NeedCard = { title: string; sub: string; icon: LucideIcon };

export const EDITORIAL_TILES: EditorialTile[] = [
  {
    "title": "Nouveautés",
    "sub": "Les dernières références en rayon",
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/visage.png"
  },
  {
    "title": "Peaux sensibles",
    "sub": "Formules sans parfum",
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/arbre-marques.png"
  },
  {
    "title": "Coffrets",
    "sub": "Prêts à offrir",
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/coffrets.png"
  }
];

export const NEEDS: NeedCard[] = [
  {
    "title": "Peau sèche & tiraillements",
    "sub": "Baumes riches, céramides et huiles nourrissantes.",
    "icon": ICONS.Droplets
  },
  {
    "title": "Imperfections",
    "sub": "Zinc, acide salicylique et nettoyants purifiants.",
    "icon": ICONS.Sparkles
  },
  {
    "title": "Anti-âge & fermeté",
    "sub": "Rétinol, vitamine C et peptides, progressivement.",
    "icon": ICONS.Star
  },
  {
    "title": "Routine complète",
    "sub": "Trois gestes validés par nos pharmaciens.",
    "icon": ICONS.ListChecks
  }
];

export const SEO_LINK_GROUPS = [
  {
    title: "Sous-catégories",
    items: ["Nettoyants visage","Sérums","Crèmes de jour","Contour des yeux","Baumes corps","Shampooings traitants","Écrans solaires","Compléments"],
  },
  {
    title: "Par besoin",
    items: ["Peaux sensibles","Peaux sèches","Imperfections","Anti-âge","Rougeurs","Chute de cheveux","Grossesse","Bébé"],
  },
  {
    title: "Marques",
    items: CATALOGUE_BRANDS,
  },
];

export const GUIDE = {
  eyebrow: "Guide d'achat",
  title: "Comment choisir sa crème hydratante ?",
  body: "Peau sèche, mixte ou réactive : nos pharmaciens décryptent les textures, les actifs à privilégier en hiver et les associations à éviter avec un traitement dermatologique.",
  cta: "Lire le guide",
  img: "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/visage.png",
};

export const SEO_INTRO = {
  eyebrow: "Le conseil Para d'Hiver",
  title: "Bien choisir sa parapharmacie en ligne",
  paragraphs: ["Une routine efficace tient en trois gestes : un nettoyant adapté à votre type de peau, un soin hydratant riche en céramides ou en acide hyaluronique, et une protection solaire portée toute l'année. En hiver, le froid et le vent fragilisent la barrière cutanée : privilégiez les textures baume et les formules sans parfum.","Tous les produits vendus sur Para d'Hiver proviennent du circuit pharmaceutique officiel et sont contrôlés par notre équipe de pharmaciens. Un doute sur une association d'actifs, une grossesse en cours ou un traitement dermatologique ? Nos pharmaciens répondent gratuitement, 7j/7."],
};
