// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

import { BadgeCheck, Droplet, Gift, Headset, Heart, Leaf, LifeBuoy, MessageCircleQuestion, ScanLine, ShieldCheck, Sparkles, Sun, Truck, type LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = { BadgeCheck, Droplet, Gift, Headset, Heart, Leaf, LifeBuoy, MessageCircleQuestion, ScanLine, ShieldCheck, Sparkles, Sun, Truck };

export type HeroSlide = {
  tag: string;
  title: string;
  sub: string;
  cta: string;
  ctaUrl: string;
  secondaryCta: string;
  secondaryCtaUrl: string;
  align: "left" | "right";
  overlay: boolean;
  bg: string;
  img: string;
  mobileImg: string;
};

export const HERO_SLIDES: HeroSlide[] = [
  {
    "tag": "Édition hiver",
    "title": "La peau protégée, tout l'hiver",
    "sub": "Sélection dermatologique testée par nos pharmaciens : barrière cutanée, froid, vent et lumière bleue.",
    "cta": "Découvrir",
    "ctaUrl": "/catalogue",
    "secondaryCta": "",
    "secondaryCtaUrl": "",
    "align": "right",
    "overlay": true,
    "bg": "linear-gradient(120deg,#2f1f3d,#5E4074 60%,#4b3563)",
    "img": "/api/cms-media/visage.png",
    "mobileImg": ""
  },
  {
    "tag": "Jusqu'à −50%",
    "title": "Ventes flash soins visage",
    "sub": "Sérums, crèmes et nettoyants des grandes marques dermatologiques à prix réduits, jusqu'à dimanche.",
    "cta": "Voir les offres",
    "ctaUrl": "/catalogue",
    "secondaryCta": "",
    "secondaryCtaUrl": "",
    "align": "right",
    "overlay": true,
    "bg": "linear-gradient(120deg,#123a44,#008AA5 65%,#0d5f70)",
    "img": "/api/cms-media/solaire.png",
    "mobileImg": ""
  },
  {
    "tag": "Nouveauté",
    "title": "Rituel corps nutrition intense",
    "sub": "Baumes, huiles sèches et cicatrisants pour les peaux très sèches. Formules sans parfum.",
    "cta": "Composer ma routine",
    "ctaUrl": "/catalogue",
    "secondaryCta": "",
    "secondaryCtaUrl": "",
    "align": "right",
    "overlay": true,
    "bg": "linear-gradient(120deg,#3a3324,#5b4e33 60%,#373020)",
    "img": "/api/cms-media/nuxe-solaire.jpg",
    "mobileImg": ""
  }
];

export type RailProductSource = "manual" | "latest" | "featured" | "bestSelling" | "category" | "brand" | "promotion";
export type RailSortOrder = "newest" | "price-asc" | "price-desc" | "name-asc" | "rating-desc";

export type RailBadgeStyle = "none" | "new" | "rank" | "team";

export type RailDef = {
  key: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  /** How lib/storefront/products.ts resolves this rail's actual products — always live, never baked in here. */
  productSource: RailProductSource;
  productIds: number[];
  category: string;
  brandFilterId: number | null;
  limit: number;
  sortOrder: RailSortOrder;
  ctaLabel: string;
  ctaUrl: string;
  badgeStyle: RailBadgeStyle;
  editorial?: { image: string; imageWidth?: number; imageHeight?: number };
};

export type BrandFeatured = { name: string; slug: string; phrase: string; img: string; ctaLabel: string };

export const RAILS: RailDef[] = [
  {
    "key": "saison",
    "eyebrow": "Sélection du moment",
    "title": "Les essentiels de la saison",
    "subtitle": "Découvrez notre sélection pensée pour prendre soin de vous au quotidien.",
    "productSource": "category",
    "productIds": [],
    "category": "Visage",
    "brandFilterId": null,
    "limit": 8,
    "sortOrder": "newest",
    "ctaLabel": "Voir tout",
    "ctaUrl": "/shop/visage",
    "badgeStyle": "none",
    "editorial": {
      "image": "/api/cms-media/arbre-marques.png",
      "imageWidth": 1024,
      "imageHeight": 1024
    }
  },
  {
    "key": "nouveautes",
    "eyebrow": "Nouveautés",
    "title": "Les nouveautés à découvrir",
    "subtitle": "Les dernières références entrées en pharmacie.",
    "productSource": "latest",
    "productIds": [],
    "category": "",
    "brandFilterId": 18,
    "limit": 8,
    "sortOrder": "newest",
    "ctaLabel": "Voir tout",
    "ctaUrl": "/catalogue",
    "badgeStyle": "none"
  },
  {
    "key": "best",
    "eyebrow": "Best sellers",
    "title": "Soins du corps",
    "subtitle": "Laits, baumes et soins ciblés",
    "productSource": "category",
    "productIds": [],
    "category": "Corps",
    "brandFilterId": null,
    "limit": 8,
    "sortOrder": "newest",
    "ctaLabel": "Voir tout",
    "ctaUrl": "/shop/corps",
    "badgeStyle": "none"
  },
  {
    "key": "rail-1788783106613",
    "eyebrow": "Sélection",
    "title": "Cheveux & cuir chevelu",
    "subtitle": "",
    "productSource": "category",
    "productIds": [],
    "category": "Cheveux",
    "brandFilterId": null,
    "limit": 8,
    "sortOrder": "newest",
    "ctaLabel": "Voir tout",
    "ctaUrl": "/shop/cheveux",
    "badgeStyle": "none",
    "editorial": {
      "image": "/api/cms-media/imgi_165_cat-2.jpg",
      "imageWidth": 1000,
      "imageHeight": 1000
    }
  }
];

export const BRANDS_FEATURED: BrandFeatured[] = [];

export const CTA_PAIR_1 = [
  {
    "eyebrow": "Dermocosmétique",
    "title": "Prenez soin de votre peau",
    "bg": "#EFE6F3",
    "img": "/api/cms-media/imgi_165_cat-3.jpg"
  },
  {
    "eyebrow": "Cheveux",
    "title": "Révélez la beauté de vos cheveux",
    "bg": "#E4F1F4",
    "img": "/api/cms-media/imgi_276_cat-70-800x800.jpg"
  }
];

export const CTA_PAIR_2 = [
  {
    "eyebrow": "Visage",
    "title": "Une routine adaptée à votre peau",
    "bg": "#F2E9F2",
    "img": "/api/cms-media/imgi_186_cat-19.jpg"
  },
  {
    "eyebrow": "Corps",
    "title": "Des soins pour chaque moment",
    "bg": "#F5F0E3",
    "img": "/api/cms-media/imgi_200_cat-42.jpg"
  }
];

export const DERMO_PICKS: { id: number; actif: string; claim: string }[] = [
  {
    "id": 221,
    "actif": "Acide hyaluronique",
    "claim": "Barrière cutanée fortifiée"
  },
  {
    "id": 77,
    "actif": "Zinc PCA",
    "claim": "Peaux grasses à imperfections"
  },
  {
    "id": 142,
    "actif": "Céramides",
    "claim": "Hydratation 24 h"
  },
  {
    "id": 32,
    "actif": "Cica",
    "claim": "Zones fragilisées, gerçures"
  },
  {
    "id": 145,
    "actif": "UVMune 400",
    "claim": "Très haute protection UVA"
  }
];

export const CTA_BANNER_COPY = {
  "eyebrow": "",
  "title": "Un conseil de pharmacien, en deux minutes",
  "description": "Décrivez votre besoin, nous vous orientons vers les produits adaptés à votre peau.",
  "ctaLabel": "Nous contacter",
  "ctaUrl": "/contact",
  "bg": "#F7EEE5",
  "textColor": "#373020",
  "ctaColor": "#5E4074"
};

export const DERMO_CORNER_COPY = {
  "eyebrow": "Dermo corner",
  "title": "La sélection dermatologique du moment",
  "subtitle": "Actifs prouvés, formules minimalistes : les références conseillées par nos pharmaciens pour les peaux réactives, sèches ou à imperfections.",
  "ctaLabel": "Voir le rayon dermo",
  "ctaUrl": "/catalogue",
  "picksTitle": "Nos soins dermo favoris",
  "img": "/api/cms-media/imgi_179_cat-13.jpg",
  "autoplay": true,
  "autoplaySpeedMs": 4500
};

export const CAMPAIGN_PRODUCT_IDS = [
  59,
  79,
  163,
  76,
  74,
  142,
  154,
  145,
  153,
  150
];

export const IMAGE_CAROUSEL_PRODUCT_IDS = [
  76,
  56,
  57,
  78,
  79
];

export const IMAGE_CAROUSEL_COPY = {
  "eyebrow": "Sélection",
  "title": "Nos incontournables du moment",
  "subtitle": "Une sélection resserrée, à retrouver aussi en boutique.",
  "ctaLabel": "Voir la sélection",
  "ctaUrl": "/catalogue",
  "picksTitle": "Notre sélection",
  "img": "/api/cms-media/ShinSpa2-780x675-1.png"
};

// `highlights[].icon` stays a plain string name (not a resolved
// lucide-react component) even though this generated file otherwise turns
// "icon": "Name" into a real component reference elsewhere — SUMMER_EDIT_COPY
// can flow through app/(site)/page.tsx (a Server Component) as a prop into
// SummerEdit (a Client Component) during preview, and a component/function
// value can't cross that boundary. SummerEdit.tsx resolves the name itself.
export type SummerEditHighlight = { icon: string; label: string };
export type SummerEditCopy = {
  eyebrow: string;
  year: string;
  title: string;
  titleAccent: string;
  description: string;
  ctaLabel: string;
  ctaUrl: string;
  img: string;
  imgMobile: string;
  imagePosition: "left" | "right";
  imageScale: number;
  overlay: boolean;
  highlights: SummerEditHighlight[];
  carousel: { autoplay: boolean; autoplaySpeedMs: number; showCounter: boolean; showProgress: boolean };
  animation: { enableReveal: boolean; enableParallax: boolean; staggerProducts: boolean; speed: "slow" | "normal" | "fast" };
  colors: { background: string; text: string; accent: string; cta: string };
  fullWidth: boolean;
};
export type SummerEditAct = { eyebrow: string; title: string; description: string; productIds: number[] };

export const SUMMER_EDIT_COPY: SummerEditCopy = {
  "eyebrow": "01 / Summer Edit",
  "year": "",
  "title": "L'été commence",
  "titleAccent": "par la peau",
  "description": "Protection solaire, hydratation intense et soins après-soleil pour une peau sublimée tout l’été.",
  "ctaLabel": "Découvrir la sélection",
  "ctaUrl": "/catalogue",
  "img": "/api/cms-media/ShinSpa2-780x675.png",
  "imgMobile": "",
  "imagePosition": "right",
  "imageScale": 1.06,
  "overlay": false,
  "highlights": [
    {
      "icon": "Sun",
      "label": "Protection solaire"
    },
    {
      "icon": "Droplet",
      "label": "Hydratation intense"
    },
    {
      "icon": "Leaf",
      "label": "Après-soleil réparateur"
    }
  ],
  "carousel": {
    "autoplay": true,
    "autoplaySpeedMs": 5000,
    "showCounter": true,
    "showProgress": true
  },
  "animation": {
    "enableReveal": true,
    "enableParallax": true,
    "staggerProducts": true,
    "speed": "normal"
  },
  "colors": {
    "background": "#F7EEE5",
    "text": "#373020",
    "accent": "#6D28D9",
    "cta": "#6D28D9"
  },
  "fullWidth": false
};

export const SUMMER_EDIT_ACTS: SummerEditAct[] = [
  {
    "eyebrow": "Acte I",
    "title": "Protéger",
    "description": "Des formules avancées pour protéger efficacement votre peau des rayons UV.",
    "productIds": []
  },
  {
    "eyebrow": "Acte II",
    "title": "Réparer",
    "description": "Hydrater, apaiser et réparer la peau après l’exposition au soleil.",
    "productIds": []
  }
];

export const TABS = ["Tous", "Visage", "Corps", "Cheveux"] as const;

export const PROMOTIONS_GRID = {
  "title": "Les offres du moment",
  "subtitle": "Profitez de nos meilleures offres.",
  "limit": 8
};

export type TrustBadge = { title: string; sub: string; icon: LucideIcon };
export const TRUST_BADGES: TrustBadge[] = [
  {
    "title": "Livraison partout au Maroc",
    "sub": "24h à Casablanca",
    "icon": ICONS.Truck
  },
  {
    "title": "Paiement 100% sécurisé",
    "sub": "CMI, carte ou à la livraison",
    "icon": ICONS.ShieldCheck
  },
  {
    "title": "Produits authentiques",
    "sub": "Circuit pharmaceutique",
    "icon": ICONS.BadgeCheck
  },
  {
    "title": "Service client expert",
    "sub": "Pharmaciens 7j/7",
    "icon": ICONS.Headset
  }
];

export const COFFRETS_COPY = {
  "eyebrow": "Idées cadeaux",
  "title": "Coffrets & cadeaux",
  "subtitle": "Des rituels prêts à offrir, emballés à la main dans nos boutiques.",
  "ctaLabel": "Tous les coffrets",
  "ctaUrl": "/collections",
  "layout": "carousel",
  "visibleDesktop": 6,
  "visibleMobile": 3
};

// Explicit type (rather than inferring from the const, as elsewhere in this
// file) because an empty CMS result would otherwise infer COFFRETS as
// never[], breaking every consumer that reads (typeof COFFRETS)[number].
export type Coffret = { tag: string; title: string; sub: string; price: number; priceFrom?: boolean; img: string; ctaLabel: string; ctaUrl: string; toast: string };

export const COFFRETS: Coffret[] = [
  {
    "tag": "Édition limitée",
    "title": "Coffret Rituel d'Hiver",
    "sub": "Nettoyant doux, sérum hydratant et baume réparateur, dans une boîte cadeau.",
    "price": 549,
    "img": "/api/cms-media/coffrets.png",
    "ctaLabel": "Offrir",
    "ctaUrl": "/catalogue",
    "toast": "Coffret Rituel d'Hiver ajouté au panier"
  },
  {
    "tag": "Best-seller",
    "title": "Coffret Peau Sensible",
    "sub": "Le duo eau thermale + cicaplast, pour les peaux réactives.",
    "price": 319,
    "img": "/api/cms-media/coffret-hall.png",
    "ctaLabel": "Offrir",
    "ctaUrl": "/catalogue",
    "toast": "Coffret Peau Sensible ajouté au panier"
  },
  {
    "tag": "PACK REPAIR",
    "title": " SHAMPOOING + APRÈS-SHAMPOOING",
    "sub": "",
    "price": 349,
    "img": "/api/cms-media/bjorn-axen-pack-repair-1.webp",
    "ctaLabel": "Offrir",
    "ctaUrl": "/produit/pack-repair-shampooing-apres-shampooing",
    "toast": ""
  },
  {
    "tag": "OFFRE SPÉCIALE FILORGA",
    "title": "Cadeau a offrir",
    "sub": " À l’achat de 3 produits FILORGA, recevez une jolie trousse Summer FILORGA OFFERTE !",
    "price": 200,
    "priceFrom": true,
    "img": "/api/cms-media/WhatsApp%20Image%202026-09-15%20at%2016.52.51.jpeg",
    "ctaLabel": "Offrir",
    "ctaUrl": "/catalogue",
    "toast": "Carte cadeau ajoutée au panier"
  }
];

export const INSTAGRAM_SECTION = {
  "ctaText": "Nous suivre",
  "ctaUrl": "https://www.instagram.com/paradhiver/",
  "postCount": 6,
  "show": true,
  "subtitle": "Routines, conseils de nos pharmaciens et coulisses de la parapharmacie.",
  "title": "Suivez-nous sur Instagram",
  "username": "paradhiver"
};

export const BRANDS: string[] = [
  "La Roche-Posay",
  "Avène",
  "Bioderma",
  "Vichy",
  "CeraVe",
  "Nuxe"
];

export type ReviewBar = { n: string; pct: number };
export const REVIEW_BARS: ReviewBar[] = [
  {
    "n": "5",
    "pct": 72
  },
  {
    "n": "4",
    "pct": 19
  },
  {
    "n": "3",
    "pct": 6
  },
  {
    "n": "2",
    "pct": 2
  },
  {
    "n": "1",
    "pct": 1
  }
];

export type SampleReview = { name: string; date: string; stars: number; text: string };
export const SAMPLE_REVIEWS: SampleReview[] = [
  {
    "name": "Salma B.",
    "date": "il y a 3 jours",
    "stars": 5,
    "text": "Texture très légère, ma peau ne tiraille plus du tout depuis le début de l'hiver. Je rachèterai."
  },
  {
    "name": "Yasmine E.",
    "date": "il y a 2 semaines",
    "stars": 5,
    "text": "Conseillé par la pharmacienne pour ma peau réactive : aucune rougeur, et la livraison à Casablanca était rapide."
  },
  {
    "name": "Nabil R.",
    "date": "le mois dernier",
    "stars": 4,
    "text": "Efficace, mais j'aurais aimé un format plus grand. Le flacon pompe est pratique au quotidien."
  }
];

export type CollectionCard = { title: string; sub: string; count: string; img: string };

export const COLLECTIONS: CollectionCard[] = [
  {
    "title": "Rituel d'hiver",
    "sub": "Nettoyer, réparer, protéger : la routine froid et vent.",
    "count": "24 produits",
    "img": "/api/cms-media/visage.png"
  },
  {
    "title": "Peaux sensibles",
    "sub": "Formules minimalistes, sans parfum, testées sous contrôle dermatologique.",
    "count": "38 produits",
    "img": "/api/cms-media/dermo.png"
  },
  {
    "title": "Cheveux & cuir chevelu",
    "sub": "Chute, pellicules, longueurs abîmées : protocoles ciblés.",
    "count": "31 produits",
    "img": "/api/cms-media/cheveux.png"
  },
  {
    "title": "Solaire toute l'année",
    "sub": "SPF 50+ visage et corps, y compris en altitude.",
    "count": "18 produits",
    "img": "/api/cms-media/solaire.png"
  },
  {
    "title": "Bébé & maman",
    "sub": "Grossesse, post-partum et peau des tout-petits.",
    "count": "27 produits",
    "img": "/api/cms-media/baby.png"
  },
  {
    "title": "Coffrets & cadeaux",
    "sub": "Rituels prêts à offrir, emballés à la main.",
    "count": "12 coffrets",
    "img": "/api/cms-media/coffrets.png"
  }
];

export const FREE_SHIPPING_THRESHOLD = 399;

export type SectionKey =
  | "hero"
  | "marketingBanner"
  | "ctaPair1"
  | "summerEdit"
  | "promotionsGrid"
  | "featuredPromo"
  | "services"
  | "coffrets"
  | "campaign"
  | "imageCarousel"
  | "dermoCorner"
  | "brandsFeatured"
  | "brandsMarquee"
  | "ctaPair2"
  | "ctaBanner"
  | "instagram"
  | "newsletter"
  | "trustBar";

/** French label per section, shown in the Storefront Builder's list. */
export const SECTION_LABELS: Record<SectionKey, string> = {
  "hero": "Bannière hero",
  "marketingBanner": "Bannière marketing (saisonnière)",
  "ctaPair1": "CTA — paire d’images (haut)",
  "summerEdit": "Summer Edit",
  "promotionsGrid": "Grille promotions",
  "featuredPromo": "Sélection + bannière promo",
  "services": "Nos services",
  "coffrets": "Coffrets / cartes cadeaux",
  "campaign": "Nos coups de cœur",
  "imageCarousel": "Image + carrousel produits",
  "dermoCorner": "Conseil dermo",
  "brandsFeatured": "Marques à l’honneur",
  "brandsMarquee": "Marques (défilement)",
  "ctaPair2": "CTA — paire d’images (bas)",
  "ctaBanner": "CTA centré",
  "instagram": "Instagram",
  "newsletter": "Newsletter",
  "trustBar": "Barre de confiance"
};

/** Which "+ Ajouter un bloc" library group each section belongs to. */
export const SECTION_GROUPS: Record<string, string> = {
  "hero": "content",
  "marketingBanner": "content",
  "ctaPair1": "content",
  "ctaPair2": "content",
  "ctaBanner": "content",
  "summerEdit": "products",
  "promotionsGrid": "products",
  "featuredPromo": "products",
  "campaign": "products",
  "imageCarousel": "products",
  "dermoCorner": "products",
  "brandsFeatured": "brands",
  "brandsMarquee": "brands",
  "services": "services",
  "coffrets": "marketing",
  "instagram": "marketing",
  "newsletter": "marketing",
  "trustBar": "marketing"
};

export const SECTION_GROUP_LABELS: Record<string, string> = {
  "content": "Contenu",
  "products": "Produits",
  "brands": "Marques",
  "services": "Services",
  "marketing": "Marketing"
};

/** Either a fixed section key, or "rail:<railKey>" addressing one specific
 * entry in RAILS — each rail is independently orderable/hideable, not
 * grouped under one shared "rails" slot. */
export type SectionEntryKey = SectionKey | `rail:${string}`;

export const SECTION_ORDER: { key: SectionEntryKey; visible: boolean }[] = [
  {
    "key": "hero",
    "visible": true
  },
  {
    "key": "ctaPair1",
    "visible": true
  },
  {
    "key": "rail:nouveautes",
    "visible": true
  },
  {
    "key": "summerEdit",
    "visible": false
  },
  {
    "key": "promotionsGrid",
    "visible": true
  },
  {
    "key": "featuredPromo",
    "visible": true
  },
  {
    "key": "rail:saison",
    "visible": true
  },
  {
    "key": "marketingBanner",
    "visible": true
  },
  {
    "key": "services",
    "visible": false
  },
  {
    "key": "coffrets",
    "visible": true
  },
  {
    "key": "campaign",
    "visible": true
  },
  {
    "key": "rail:best",
    "visible": true
  },
  {
    "key": "imageCarousel",
    "visible": false
  },
  {
    "key": "dermoCorner",
    "visible": true
  },
  {
    "key": "brandsFeatured",
    "visible": false
  },
  {
    "key": "brandsMarquee",
    "visible": true
  },
  {
    "key": "rail:rail-1788783106613",
    "visible": true
  },
  {
    "key": "ctaPair2",
    "visible": true
  },
  {
    "key": "ctaBanner",
    "visible": true
  },
  {
    "key": "instagram",
    "visible": false
  },
  {
    "key": "newsletter",
    "visible": true
  },
  {
    "key": "trustBar",
    "visible": true
  }
];

export const CAMPAIGN_COPY = {
  "eyebrow": "Sélection",
  "title": "Nos coups de cœur",
  "description": "Les références que nos pharmaciens recommandent le plus, réunies dans une sélection à part.",
  "ctaLabel": "Voir la sélection",
  "ctaUrl": "/catalogue",
  "railTitle": "Nos coups de cœur",
  "img": "/api/cms-media/imgi_242_cat-41.jpg"
};

export const MARKETING_BANNERS = [
  {
    "campaign": "campagne-2026-09-07",
    "imageMode": "overlay",
    "eyebrow": "",
    "title": "",
    "description": "",
    "ctaLabel": "",
    "ctaUrl": "/catalogue",
    "badgeLabel": "",
    "active": true,
    "startDate": "",
    "endDate": "",
    "img": "/api/cms-media/ChatGPT%20Image%2017%20ao%C3%BBt%202026%2C%2013_44_36.png",
    "imgMobile": ""
  }
];

export const NEWSLETTER_COPY = {
  "title": "Recevez nos conseils & nouveautés",
  "subtitle": "Inscrivez-vous pour découvrir nos conseils pharmaceutiques, nouveautés et offres exclusives.",
  "placeholder": "Votre adresse email",
  "buttonLabel": "S'inscrire",
  "successMessage": "Merci ! Votre code −10% arrive par email",
  "logoEnabled": true,
  "logoSize": 76,
  "logoPosition": "left",
  "backgroundColor": "#5E4074",
  "textColor": "#FFFFFF",
  "ctaColor": "#008AA5",
  "borderRadius": 26,
  "particlesEnabled": true,
  "particlesOpacity": 0.18
};

export const SERVICES_TEASER = [];
