// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

// Primary navigation and the hover mega-menu columns shown underneath it.
// Source: the "navigation" Payload global, edited from the Storefront
// Builder's "Navigation" tab (/dashboard/storefront) — decoupled from the
// Categories collection on purpose (see backend/src/globals/Navigation.ts).
// Every href is resolved from a real category/brand relationship or a
// curated existing route — never "#" and never a blanket /catalogue
// fallback except when a relationship is genuinely unset.

/** "custom" means the editor supplied free hex values in bgColor/textColor;
 * the named colors resolve to theme CSS variables instead. */
export type NavBadge = {
  label: string;
  color: "plum" | "teal" | "sale" | "custom";
  bgColor?: string;
  textColor?: string;
};

export type NavAppearance = {
  color?: string;
  hoverColor?: string;
  activeColor?: string;
  backgroundColor?: string;
  /** Thin outline around the link. Configured per item in the CMS. */
  borderColor?: string;
  fontWeight?: string;
  /** 0–1. Absent means "not configured" and inherits the CSS fallback of 1,
   * which is why it is optional rather than defaulted here. */
  opacity?: number;
};

export type NavAnimationType = "blink" | "pulse" | "shimmer" | "glow";

export type NavAnimation = {
  type: NavAnimationType;
  duration: number;
  delay: number;
  /** "infinite" or a stringified integer. */
  iterationCount: string;
};
/** A mega-menu link is styled by the very same appearance/animation groups a
 * top-level nav item is (see the CMS's shared appearance group), and
 * lib/navStyle.ts renders both through one code path — so it carries the same
 * optional fields. They were configurable in the CMS and mapped by
 * siteChromeContent long before this type admitted they existed. */
export type MegaLink = {
  label: string;
  href: string;
  openInNewTab?: boolean;
  appearance?: NavAppearance;
  animation?: NavAnimation;
};
export type MegaColumn = { title: string; links: MegaLink[] };
export type MegaPromo = { img: string; title: string; description: string; ctaLabel: string; ctaUrl: string };
export type MegaMenuContent = { subtitle: string; columns: MegaColumn[]; promo: MegaPromo | null };

export type NavItem = {
  label: string;
  href: string;
  /** Key into MEGA_MENU; omitted means no mega menu (e.g. Services). */
  megaKey?: string;
  badge?: NavBadge;
  openInNewTab?: boolean;
  /** Absent when the editor left every colour blank — the item then renders
   * with the theme colours exactly as it did before these fields existed. */
  appearance?: NavAppearance;
  /** Absent when disabled or set to "none". */
  animation?: NavAnimation;
};

export const NAV_ITEMS: NavItem[] = [
  {
    "href": "/shop/soldes",
    "label": "Soldes",
    "megaKey": "Soldes",
    "badge": {
      "label": "-40%",
      "color": "sale"
    },
    "appearance": {
      "color": "#4a25d0",
      "hoverColor": "#0c0c0d"
    }
  },
  {
    "href": "/shop/marques",
    "label": "Marques",
    "megaKey": "Marques"
  },
  {
    "href": "/shop/visage",
    "label": "Visage",
    "megaKey": "Visage"
  },
  {
    "href": "/shop/cheveux",
    "label": "Cheveux",
    "megaKey": "Cheveux"
  },
  {
    "href": "/shop/corps",
    "label": "Corps",
    "megaKey": "Corps"
  },
  {
    "href": "/shop/k-beauty",
    "label": "K Beauty",
    "megaKey": "K Beauty"
  },
  {
    "href": "/shop/maquillage",
    "label": "Maquillage",
    "megaKey": "Maquillage"
  },
  {
    "href": "/shop/bebe-maman",
    "label": "Bébé & Maman",
    "megaKey": "Bébé & Maman"
  },
  {
    "href": "/shop/bucco-dentaire",
    "label": "Bucco-dentaire",
    "megaKey": "Bucco-dentaire"
  },
  {
    "href": "/shop/complements-alimentaires",
    "label": "Compléments alimentaires",
    "megaKey": "Compléments alimentaires"
  }
];

export const MEGA_MENU: Record<string, MegaMenuContent> = {
  "Soldes": {
    "subtitle": "",
    "columns": [
      {
        "title": "Promotions",
        "links": [
          {
            "href": "/shop/ventes-flash",
            "label": "Ventes flash"
          },
          {
            "href": "/shop/jusqu-a-50",
            "label": "Jusqu'à -50%"
          },
          {
            "href": "/shop/fins-de-serie",
            "label": "Fins de série"
          },
          {
            "href": "/shop/derniers-coups-de-c-ur",
            "label": "Derniers coups de cœur"
          }
        ]
      }
    ],
    "promo": null
  },
  "Marques": {
    "subtitle": "",
    "columns": [
      {
        "title": "Dermocosmétique",
        "links": [
          {
            "href": "/shop/la-roche-posay",
            "label": "La Roche-Posay"
          },
          {
            "href": "/shop/avene",
            "label": "Avène"
          },
          {
            "href": "/shop/bioderma",
            "label": "Bioderma"
          },
          {
            "href": "/shop/cerave",
            "label": "CeraVe"
          },
          {
            "href": "/shop/vichy",
            "label": "Vichy"
          },
          {
            "href": "/shop/uriage",
            "label": "Uriage"
          }
        ]
      },
      {
        "title": "Autres marques",
        "links": [
          {
            "href": "/shop/nuxe",
            "label": "Nuxe"
          },
          {
            "href": "/shop/klorane",
            "label": "Klorane"
          },
          {
            "href": "/shop/ducray",
            "label": "Ducray"
          },
          {
            "href": "/shop/mustela",
            "label": "Mustela"
          },
          {
            "href": "/shop/lierac",
            "label": "Lierac"
          },
          {
            "href": "/shop/svr",
            "label": "SVR"
          }
        ]
      }
    ],
    "promo": null
  },
  "Visage": {
    "subtitle": "",
    "columns": [
      {
        "title": "Nettoyants",
        "links": [
          {
            "href": "/shop/eaux-micellaires",
            "label": "Eaux micellaires"
          },
          {
            "href": "/shop/gels-moussants",
            "label": "Gels moussants"
          },
          {
            "href": "/shop/demaquillants",
            "label": "Démaquillants"
          },
          {
            "href": "/shop/lotions-toniques",
            "label": "Lotions toniques"
          }
        ]
      },
      {
        "title": "Sérums",
        "links": [
          {
            "href": "/shop/anti-taches",
            "label": "Anti-taches"
          },
          {
            "href": "/shop/anti-age",
            "label": "Anti-âge"
          },
          {
            "href": "/shop/hydratants",
            "label": "Hydratants"
          },
          {
            "href": "/shop/vitamine-c",
            "label": "Vitamine C"
          }
        ]
      },
      {
        "title": "Crèmes",
        "links": [
          {
            "href": "/shop/peaux-seches",
            "label": "Peaux sèches"
          },
          {
            "href": "/shop/peaux-sensibles",
            "label": "Peaux sensibles"
          },
          {
            "href": "/shop/contour-des-yeux",
            "label": "Contour des yeux"
          },
          {
            "href": "/shop/nuit",
            "label": "Nuit"
          }
        ]
      },
      {
        "title": "Masques",
        "links": [
          {
            "href": "/shop/purifiants",
            "label": "Purifiants"
          },
          {
            "href": "/shop/hydratants",
            "label": "Hydratants"
          },
          {
            "href": "/shop/peelings-doux",
            "label": "Peelings doux"
          },
          {
            "href": "/shop/patchs",
            "label": "Patchs"
          }
        ]
      }
    ],
    "promo": null
  },
  "Cheveux": {
    "subtitle": "",
    "columns": [
      {
        "title": "Shampoings & soins",
        "links": [
          {
            "href": "/shop/shampoings-traitants",
            "label": "Shampoings traitants"
          },
          {
            "href": "/shop/apres-shampoings",
            "label": "Après-shampoings"
          },
          {
            "href": "/shop/masques-capillaires",
            "label": "Masques capillaires"
          },
          {
            "href": "/shop/serums-cheveux",
            "label": "Sérums cheveux"
          }
        ]
      },
      {
        "title": "Besoins",
        "links": [
          {
            "href": "/shop/chute-de-cheveux",
            "label": "Chute de cheveux"
          },
          {
            "href": "/shop/pellicules",
            "label": "Pellicules"
          },
          {
            "href": "/shop/cheveux-secs",
            "label": "Cheveux secs"
          },
          {
            "href": "/shop/cuir-chevelu-sensible",
            "label": "Cuir chevelu sensible"
          }
        ]
      }
    ],
    "promo": null
  },
  "Corps": {
    "subtitle": "",
    "columns": [
      {
        "title": "Hygiène",
        "links": [
          {
            "href": "/shop/gels-et-huiles-lavants",
            "label": "Gels et huiles lavants"
          },
          {
            "href": "/shop/savon-dermatologique",
            "label": "Savon dermatologique"
          },
          {
            "href": "/shop/deodorants",
            "label": "Déodorants"
          },
          {
            "href": "/shop/anti-transpirants",
            "label": "Anti-transpirants"
          },
          {
            "href": "/shop/hygiene-intime",
            "label": "Hygiène intime"
          }
        ]
      },
      {
        "title": "Soins ciblés",
        "links": [
          {
            "href": "/shop/cremes-cicatrisantes",
            "label": "Crèmes cicatrisantes"
          },
          {
            "href": "/shop/cellulite-vergetures",
            "label": "Cellulite & vergetures"
          },
          {
            "href": "/shop/huiles-cremes-minceur",
            "label": "Huiles & crèmes minceur"
          },
          {
            "href": "/shop/soins-mains-pieds",
            "label": "Soins mains & pieds"
          }
        ]
      },
      {
        "title": "Hydratation",
        "links": [
          {
            "href": "/shop/laits-corps",
            "label": "Laits corps"
          },
          {
            "href": "/shop/baumes-reparateurs",
            "label": "Baumes réparateurs"
          },
          {
            "href": "/shop/gommages-exfoliants",
            "label": "Gommages & exfoliants"
          },
          {
            "href": "/shop/huiles-seches",
            "label": "Huiles sèches"
          }
        ]
      },
      {
        "title": "Épilation",
        "links": [
          {
            "href": "/shop/cremes-depilatoires",
            "label": "Crèmes dépilatoires"
          },
          {
            "href": "/shop/epilateurs",
            "label": "Épilateurs"
          },
          {
            "href": "/shop/apres-epilation",
            "label": "Après-épilation"
          },
          {
            "href": "/shop/accessoires",
            "label": "Accessoires"
          }
        ]
      }
    ],
    "promo": null
  },
  "K Beauty": {
    "subtitle": "",
    "columns": [
      {
        "title": "Rituel coréen",
        "links": [
          {
            "href": "/shop/nettoyants",
            "label": "Nettoyants"
          },
          {
            "href": "/shop/essences-serums",
            "label": "Essences & sérums"
          },
          {
            "href": "/shop/masques-tissu",
            "label": "Masques tissu"
          },
          {
            "href": "/shop/cremes-hydratantes",
            "label": "Crèmes hydratantes"
          }
        ]
      }
    ],
    "promo": null
  },
  "Maquillage": {
    "subtitle": "",
    "columns": [
      {
        "title": "Teint",
        "links": [
          {
            "href": "/shop/fond-de-teint",
            "label": "Fond de teint"
          },
          {
            "href": "/shop/correcteurs",
            "label": "Correcteurs"
          },
          {
            "href": "/shop/poudres",
            "label": "Poudres"
          }
        ]
      },
      {
        "title": "Yeux & sourcils",
        "links": [
          {
            "href": "/shop/mascaras",
            "label": "Mascaras"
          },
          {
            "href": "/shop/eyeliners",
            "label": "Eyeliners"
          },
          {
            "href": "/shop/sourcils",
            "label": "Sourcils"
          }
        ]
      },
      {
        "title": "Lèvres",
        "links": [
          {
            "href": "/shop/rouges-a-levres",
            "label": "Rouges à lèvres"
          },
          {
            "href": "/shop/baumes-teintes",
            "label": "Baumes teintés"
          },
          {
            "href": "/shop/gloss",
            "label": "Gloss"
          }
        ]
      }
    ],
    "promo": null
  },
  "Bébé & Maman": {
    "subtitle": "",
    "columns": [
      {
        "title": "Bébé",
        "links": [
          {
            "href": "/shop/soins-du-change",
            "label": "Soins du change"
          },
          {
            "href": "/shop/toilette-douce",
            "label": "Toilette douce"
          },
          {
            "href": "/shop/cremes-hydratantes",
            "label": "Crèmes hydratantes"
          },
          {
            "href": "/shop/solaire-bebe",
            "label": "Solaire bébé"
          }
        ]
      },
      {
        "title": "Maman",
        "links": [
          {
            "href": "/shop/grossesse",
            "label": "Grossesse"
          },
          {
            "href": "/shop/allaitement",
            "label": "Allaitement"
          },
          {
            "href": "/shop/vergetures",
            "label": "Vergetures"
          }
        ]
      }
    ],
    "promo": null
  },
  "Bucco-dentaire": {
    "subtitle": "",
    "columns": [
      {
        "title": "Hygiène bucco-dentaire",
        "links": [
          {
            "href": "/shop/dentifrices",
            "label": "Dentifrices"
          },
          {
            "href": "/shop/brosses-a-dents",
            "label": "Brosses à dents"
          },
          {
            "href": "/shop/bains-de-bouche",
            "label": "Bains de bouche"
          },
          {
            "href": "/shop/fil-dentaire",
            "label": "Fil dentaire"
          }
        ]
      }
    ],
    "promo": null
  },
  "Compléments alimentaires": {
    "subtitle": "",
    "columns": [
      {
        "title": "Compléments",
        "links": [
          {
            "href": "/shop/vitalite-immunite",
            "label": "Vitalité & immunité"
          },
          {
            "href": "/shop/cheveux-ongles",
            "label": "Cheveux & ongles"
          },
          {
            "href": "/shop/sommeil-stress",
            "label": "Sommeil & stress"
          },
          {
            "href": "/shop/digestion",
            "label": "Digestion"
          }
        ]
      }
    ],
    "promo": null
  }
};
