// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

// Primary navigation and the hover mega-menu columns shown underneath it.
// Source: the "navigation" Payload global, edited from the Storefront
// Builder's "Navigation" tab (/dashboard/storefront) — decoupled from the
// Categories collection on purpose (see backend/src/globals/Navigation.ts).
// Every href is resolved from a real category/brand relationship or a
// curated existing route — never "#" and never a blanket /catalogue
// fallback except when a relationship is genuinely unset.

/** "custom" means the editor supplied free hex values in bgColor/textColor;
 * the named colors resolve to theme CSS variables instead. */
export type NavBadge = {
  label: string;
  color: "plum" | "teal" | "sale" | "custom";
  bgColor?: string;
  textColor?: string;
};

export type NavAppearance = {
  color?: string;
  hoverColor?: string;
  activeColor?: string;
  backgroundColor?: string;
  /** Thin outline around the link. Configured per item in the CMS. */
  borderColor?: string;
  fontWeight?: string;
  /** 0–1. Absent means "not configured" and inherits the CSS fallback of 1,
   * which is why it is optional rather than defaulted here. */
  opacity?: number;
};

export type NavAnimationType = "blink" | "pulse" | "shimmer" | "glow";

export type NavAnimation = {
  type: NavAnimationType;
  duration: number;
  delay: number;
  /** "infinite" or a stringified integer. */
  iterationCount: string;
};
export type MegaLink = {
  label: string;
  href: string;
  openInNewTab?: boolean;
  appearance?: NavAppearance;
  animation?: NavAnimation;
};
export type MegaColumn = { title: string; links: MegaLink[] };
export type MegaPromo = { img: string; title: string; description: string; ctaLabel: string; ctaUrl: string };
export type MegaMenuContent = { subtitle: string; columns: MegaColumn[]; promo: MegaPromo | null };

export type NavItem = {
  label: string;
  href: string;
  /** Key into MEGA_MENU; omitted means no mega menu (e.g. Services). */
  megaKey?: string;
  badge?: NavBadge;
  openInNewTab?: boolean;
  /** Absent when the editor left every colour blank — the item then renders
   * with the theme colours exactly as it did before these fields existed. */
  appearance?: NavAppearance;
  /** Absent when disabled or set to "none". */
  animation?: NavAnimation;
};

export const NAV_ITEMS: NavItem[] = [];

export const MEGA_MENU: Record<string, MegaMenuContent> = {};

/** The round category shortcuts above the hero. `enabled` is opt-in: a shop
 * that never configured the strip must not suddenly grow one because a sync
 * ran. `image` is omitted per chip rather than emitted empty — the strip
 * renders as tiles only when every configured chip has one. */
export const CATEGORY_STRIP: {
  enabled: boolean;
  showAllChip: boolean;
  allChipLabel: string;
  items: { label: string; href: string; image?: string }[];
} = {
  "allChipLabel": "Tout",
  "enabled": true,
  "items": [
    {
      "href": "/shop/visage",
      "label": "Visage",
      "image": "/api/cms-media/imgi_165_cat-4.jpg"
    },
    {
      "href": "/shop/cheveux",
      "label": "Cheveux",
      "image": "/api/cms-media/imgi_255_cat-61-800x800.jpg"
    },
    {
      "href": "/shop/corps",
      "label": "Corps",
      "image": "/api/cms-media/imgi_185_cat-19-800x800-1.jpg"
    },
    {
      "href": "/shop/bebe-maman",
      "label": "Bébé & Maman",
      "image": "/api/cms-media/imgi_283_cat-85-800x800.jpg"
    },
    {
      "href": "/shop/maquillage",
      "label": "Maquillage",
      "image": "/api/cms-media/imgi_283_cat-85-800x800-1.jpg"
    },
    {
      "href": "/shop/complements-alimentaires",
      "label": "Compléments",
      "image": "/api/cms-media/complements.png"
    }
  ],
  "showAllChip": false
};
