// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

import { Baby, Feather, Palette, ScanFace, Scissors, Droplet, type LucideIcon } from "lucide-react";

const ICONS: Record<string, LucideIcon> = { Baby, Feather, Palette, ScanFace, Scissors, Droplet };

export type ServiceStep = { n: string; title: string; sub: string };

export type Service = {
  id: number;
  img: string;
  title: string;
  sub: string;
  price: number; // 0 means "Offert" (free)
  duration: string;
  expert: string;
  bg: string;
  icon: LucideIcon;
  desc: string;
  benefits: string[];
  steps: ServiceStep[];
};

export const SERVICES: Service[] = [
  {
    "id": 6,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/baby.png",
    "title": "Atelier future maman",
    "sub": "Routine grossesse et post-partum, sélection de soins sûrs pour vous et bébé.",
    "price": 0,
    "duration": "60 min",
    "expert": "Pharmacienne",
    "bg": "#F2E9F2",
    "icon": ICONS.Baby,
    "desc": "Un atelier en petit comité pour composer une routine sûre pendant la grossesse et l'allaitement : ingrédients à éviter, vergetures, peau du nourrisson et premiers gestes d'hygiène.",
    "benefits": [
      "Liste d'ingrédients à éviter",
      "Routine vergetures et tiraillements",
      "Soins bébé validés pédiatrie",
      "Atelier en petit groupe (6 personnes)"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Accueil",
        "sub": "Tour de table et attentes."
      },
      {
        "n": "2",
        "title": "Ingrédients",
        "sub": "Ce qu'on évite, ce qu'on garde."
      },
      {
        "n": "3",
        "title": "Routine",
        "sub": "Corps, visage et soins bébé."
      },
      {
        "n": "4",
        "title": "Questions",
        "sub": "Échange libre avec la pharmacienne."
      }
    ]
  },
  {
    "id": 5,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/arbre-marques.png",
    "title": "Épilation",
    "sub": "Cire tiède hypoallergénique, protocole apaisant avant et après séance.",
    "price": 99,
    "duration": "20 min",
    "expert": "Esthéticienne",
    "bg": "#EAF3F0",
    "icon": ICONS.Feather,
    "desc": "Épilation à la cire tiède hypoallergénique, précédée d'un nettoyage antiseptique doux et suivie d'un soin apaisant post-épilation pour limiter rougeurs et poils incarnés.",
    "benefits": [
      "Cire tiède hypoallergénique",
      "Soin apaisant post-épilation inclus",
      "Zones visage et corps",
      "Conseils anti-poils incarnés"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Préparation",
        "sub": "Nettoyage antiseptique de la zone."
      },
      {
        "n": "2",
        "title": "Épilation",
        "sub": "Cire tiède, travail par bandes."
      },
      {
        "n": "3",
        "title": "Apaisement",
        "sub": "Soin calmant et rafraîchissant."
      },
      {
        "n": "4",
        "title": "Conseils",
        "sub": "Gommage et hydratation à domicile."
      }
    ]
  },
  {
    "id": 4,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/maquillage.png",
    "title": "Conseil maquillage",
    "sub": "Teint, correction et sélection de produits adaptés à votre carnation.",
    "price": 249,
    "duration": "45 min",
    "expert": "Make-up artist",
    "bg": "#F3EEF7",
    "icon": ICONS.Palette,
    "desc": "Une séance pour trouver la bonne teinte de fond de teint et apprendre des gestes simples : correction des rougeurs, sublimation du regard, tenue longue durée. Le montant est déduit de vos achats du jour.",
    "benefits": [
      "Recherche de teinte en lumière neutre",
      "Gestes simples à reproduire seule",
      "Déduit de vos achats du jour",
      "Sélection adaptée aux peaux sensibles"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Analyse",
        "sub": "Carnation, sous-ton et attentes."
      },
      {
        "n": "2",
        "title": "Teint",
        "sub": "Test de 2 à 3 teintes en lumière du jour."
      },
      {
        "n": "3",
        "title": "Démonstration",
        "sub": "Application guidée sur un demi-visage."
      },
      {
        "n": "4",
        "title": "Sélection",
        "sub": "Liste des produits testés."
      }
    ]
  },
  {
    "id": 3,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/cheveux.png",
    "title": "Soin capillaire",
    "sub": "Diagnostic du cuir chevelu et soin ciblé chute, pellicules ou cheveux abîmés.",
    "price": 199,
    "duration": "40 min",
    "expert": "Experte cheveux",
    "bg": "#F5F0E3",
    "icon": ICONS.Scissors,
    "desc": "Diagnostic du cuir chevelu à la caméra, puis soin traitant appliqué en cabine : lotion anti-chute, protocole anti-pellicules ou masque de reconstruction selon le besoin identifié.",
    "benefits": [
      "Diagnostic caméra du cuir chevelu",
      "Soin traitant appliqué en cabine",
      "Protocole à poursuivre à la maison",
      "Suivi photo d'une séance à l'autre"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Diagnostic",
        "sub": "Caméra cuir chevelu et fibre."
      },
      {
        "n": "2",
        "title": "Nettoyage",
        "sub": "Shampooing adapté au diagnostic."
      },
      {
        "n": "3",
        "title": "Soin",
        "sub": "Application du traitement ciblé."
      },
      {
        "n": "4",
        "title": "Conseils",
        "sub": "Routine et fréquence recommandées."
      }
    ]
  },
  {
    "id": 2,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/visage.png",
    "title": "Soin du visage éclat",
    "sub": "Nettoyage profond, gommage doux et masque hydratant adaptés aux peaux sensibles.",
    "price": 299,
    "duration": "45 min",
    "expert": "Esthéticienne",
    "bg": "#F5E8EC",
    "icon": ICONS.Droplet,
    "desc": "Un protocole en cabine pensé pour les peaux fatiguées par le froid : double nettoyage, exfoliation enzymatique, massage drainant et masque hydratant. Sans parfum, adapté aux peaux réactives.",
    "benefits": [
      "Teint visiblement plus lumineux",
      "Peau repulpée et confortable",
      "Protocole sans parfum ni alcool",
      "Convient aux peaux réactives"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Double nettoyage",
        "sub": "Huile démaquillante puis gel doux."
      },
      {
        "n": "2",
        "title": "Exfoliation",
        "sub": "Gommage enzymatique sans grains."
      },
      {
        "n": "3",
        "title": "Massage",
        "sub": "Drainage visage et cou, 10 minutes."
      },
      {
        "n": "4",
        "title": "Masque",
        "sub": "Masque hydratant + soin de finition."
      }
    ]
  },
  {
    "id": 1,
    "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/dermo.png",
    "title": "Diagnostic de peau",
    "sub": "Analyse complète du teint, de l'hydratation et de la sensibilité, avec une routine sur mesure.",
    "price": 0,
    "duration": "30 min",
    "expert": "Pharmacien",
    "bg": "#EFE6F3",
    "icon": ICONS.ScanFace,
    "desc": "Un bilan cutané complet réalisé par un pharmacien : mesure de l'hydratation, analyse de la sensibilité et des zones à imperfections. Vous repartez avec une routine écrite, adaptée à votre peau et à votre budget.",
    "benefits": [
      "Bilan objectif de votre type de peau",
      "Routine matin et soir écrite",
      "Recommandations produits sans obligation d'achat",
      "Suivi à 6 semaines offert"
    ],
    "steps": [
      {
        "n": "1",
        "title": "Questionnaire",
        "sub": "Habitudes, sensibilités, traitements en cours."
      },
      {
        "n": "2",
        "title": "Mesures",
        "sub": "Hydratation, sébum et sensibilité par zone."
      },
      {
        "n": "3",
        "title": "Analyse",
        "sub": "Lecture des résultats avec le pharmacien."
      },
      {
        "n": "4",
        "title": "Routine",
        "sub": "Prescription cosmétique remise par écrit."
      }
    ]
  }
];

export function getService(id: number): Service {
  return SERVICES.find((s) => s.id === id) ?? SERVICES[0];
}

export function servicePriceLabel(service: Service): string {
  if (!service.price) return "Offert";
  return `${service.price.toLocaleString("fr-FR")} MAD`;
}
