// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

// Global chrome (Top Bar, Header, Footer) shown on every route. Source: the
// "site-chrome" Payload global, edited from the Storefront Builder's
// "Global" tab (/dashboard/storefront) — one edit here reaches every page.
//
// `icon` stays a plain string name (not a resolved lucide-react component)
// even though this file otherwise turns "icon": "Name" into a real
// component reference elsewhere (see withIconRefs) — HEADER_ACTIONS can flow
// through app/(site)/layout.tsx (a Server Component) as a prop into Header
// (a Client Component) during preview, and a component/function value
// can't cross that boundary. Header.tsx resolves the name to a component
// itself.

export type TopBarConfig = { enabled: boolean; messages: string[]; marqueeSpeedSec: number; mobileMessage: string };
export type Logo = { img: string; wordmark: string; href: string };
export type HeaderSearchConfig = { enabled: boolean; placeholder: string };
export type HeaderAction = { key: string; label: string; icon: string; href: string };
export type FooterLink = { label: string; href: string };
export type FooterColumn = { title: string; links: FooterLink[] };

export const TOPBAR_CONFIG: TopBarConfig = {
  "enabled": true,
  "messages": [
    "Des remises exceptionnelles : -40% -50% -60% sur une sélection de produits, profitez-en vite",
    "Livraison partout au Maroc",
    "Paiement 100% sécurisé",
    "Produits authentiques garantis",
    "Conseil pharmacien gratuit",
    "Livraison offerte dès 399 MAD"
  ],
  "marqueeSpeedSec": 34,
  "mobileMessage": "Livraison offerte dès 399 MAD"
};

export const LOGO: Logo = {
  "img": "https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/logo.png",
  "wordmark": "PARA D'HIVER",
  "href": "/"
};

export const HEADER_SEARCH: HeaderSearchConfig = {
  "enabled": true,
  "placeholder": "Rechercher un produit, une marque…"
};

export const HEADER_ACTIONS: HeaderAction[] = [
  {
    "key": "services",
    "label": "Magasin et services",
    "icon": "MapPin",
    "href": "/services"
  },
  {
    "key": "contact",
    "label": "Contact",
    "icon": "Phone",
    "href": "/contact"
  },
  {
    "key": "favoris",
    "label": "Favoris",
    "icon": "Heart",
    "href": ""
  },
  {
    "key": "panier",
    "label": "Panier",
    "icon": "ShoppingBag",
    "href": ""
  }
];

export const FOOTER_COLUMNS: FooterColumn[] = [
  {
    "title": "À propos",
    "links": [
      {
        "label": "Notre pharmacie",
        "href": "/services"
      },
      {
        "label": "Nos pharmaciens",
        "href": "/services"
      },
      {
        "label": "Contact",
        "href": "/contact"
      }
    ]
  },
  {
    "title": "Boutique",
    "links": [
      {
        "label": "Produits",
        "href": "/shop"
      },
      {
        "label": "Marques",
        "href": "/marques"
      },
      {
        "label": "Promotions",
        "href": "/shop/soldes"
      },
      {
        "label": "Nouveautés",
        "href": "/shop/nouveautes"
      }
    ]
  },
  {
    "title": "Conseils",
    "links": [
      {
        "label": "Conseils pharmaceutiques",
        "href": "/services"
      },
      {
        "label": "Articles",
        "href": "/services"
      },
      {
        "label": "Routines",
        "href": "/services"
      },
      {
        "label": "Préoccupations",
        "href": "/services"
      }
    ]
  },
  {
    "title": "Services",
    "links": [
      {
        "label": "Livraison",
        "href": "/services"
      },
      {
        "label": "Scanner ordonnance",
        "href": "/services"
      },
      {
        "label": "Contact",
        "href": "/contact"
      },
      {
        "label": "FAQ",
        "href": "/services"
      }
    ]
  }
];
