// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

export type StoreHours = { days: string; hours: string };

export type Store = {
  name: string;
  address: string;
  phone: string;
  email: string;
  hours: StoreHours[];
  mapUrl: string;
};

export const STORES: Store[] = [
  {
    "address": "4A Allée des Amandiers, Aïn Sebaâ, Casablanca 20000",
    "email": "paradhiver@gmail.com",
    "hours": [
      {
        "days": "Horaires à compléter",
        "hours": "—"
      }
    ],
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=4A%20All%C3%A9e%20des%20Amandiers%2C%20A%C3%AFn%20Seba%C3%A2%2C%20Casablanca%2020000",
    "name": "Para d'Hiver — Aïn Sebaâ",
    "phone": "06 19 96 90 07"
  }
];
