// AUTO-GENERATED by `npm run sync-cms` — do not edit by hand.
// Source of truth is the Payload CMS admin (backend/). Re-run the sync after
// editing content there; this file is overwritten on every run.

// Site-wide color theme. Source: the "theme" Payload global, edited from
// the Storefront Builder's "Apparence" tab (/dashboard/storefront).

export type Theme = {
  preset: string;
  colorPrimary: string;
  colorSecondary: string;
  colorAccent: string;
  colorSale: string;
  colorTextPrimary: string;
  colorTextMuted: string;
  colorBackgroundSecondary: string;
  buttonBg: string;
  buttonText: string;
  buttonHoverBg: string;
  buttonHoverText: string;
  buttonRadius: number;
  buttonFontWeight: number;
  buttonLetterSpacing: number;
  badgeBg: string;
  badgeText: string;
  badgeFontSize: number;
  badgeFontWeight: number;
  badgeLetterSpacing: number;
  badgeRadius: number;
  badgePaddingX: number;
  badgePaddingY: number;
  badgeGap: number;
};

export const THEME: Theme = {
  "preset": "parad-hiver",
  "colorPrimary": "#5E4074",
  "colorSecondary": "#008AA5",
  "colorAccent": "#5FBE00",
  "colorSale": "#FF514D",
  "colorTextPrimary": "#373020",
  "colorTextMuted": "#757D86",
  "colorBackgroundSecondary": "#F7EEE5",
  "buttonBg": "#5E4074",
  "buttonText": "#FFFFFF",
  "buttonHoverBg": "#432951",
  "buttonHoverText": "#FFFFFF",
  "buttonRadius": 999,
  "buttonFontWeight": 600,
  "buttonLetterSpacing": 0.08,
  "badgeBg": "#5E4074",
  "badgeText": "#FFFFFF",
  "badgeFontSize": 10.5,
  "badgeFontWeight": 600,
  "badgeLetterSpacing": 0.06,
  "badgeRadius": 999,
  "badgePaddingX": 11,
  "badgePaddingY": 5,
  "badgeGap": 6
};
