import type { Category } from "@/data/products";

/**
 * The nine catalogue universes, as shown by the "Explorer nos univers"
 * carousel.
 *
 * This lives in lib/ rather than data/ on purpose: everything under data/ is
 * regenerated by `npm run sync-cms` from Payload, and a hand-written constant
 * there would be silently overwritten on the next sync. The Categories
 * collection has no image field (name, slug, parent, order, isActive, icon),
 * so the editorial shot below cannot come from the CMS today.
 *
 * `category` matches the Products.category enum exactly, which is what makes
 * the counts and the filtering real: the carousel reads its numbers from the
 * catalogue facets, never from a hard-coded figure.
 */
export type Universe = {
  category: Category;
  blurb: string;
  /**
   * An existing Cloudinary editorial shot, or null when none exists for this
   * universe yet. Null renders the typographic card instead of borrowing an
   * unrelated photo — a face-cream shot on "Bucco-Dentaire" would misrepresent
   * the aisle, and the same rule already governs PRODUCT_PLACEHOLDER.
   */
  image: string | null;
};

const SHOT = (name: string) => `https://res.cloudinary.com/draqxinrp/image/upload/para-dhiver/${name}`;

export const UNIVERSES: Universe[] = [
  { blurb: "Nettoyants, sérums, hydratants et soins ciblés", category: "Visage", image: SHOT("visage.png") },
  // dermo.png and arbre-hiver.png are both neutral bathroom-counter scenes of
  // dermocosmetic bottles — generic enough to stand for body care and daily
  // hygiene without claiming a product that isn't there. Replace them the day
  // corps.png / hygiene.png are uploaded.
  { blurb: "Hydratation, baumes et soins du corps", category: "Corps", image: SHOT("dermo.png") },
  { blurb: "Shampooings, soins et traitements", category: "Cheveux", image: SHOT("cheveux.png") },
  { blurb: "Protection solaire visage et corps", category: "Solaire", image: SHOT("solaire.png") },
  { blurb: "Les essentiels pour bébé et maman", category: "Baby & Mom", image: SHOT("baby.png") },
  { blurb: "Teint, lèvres et regard", category: "Maquillage", image: SHOT("maquillage.png") },
  { blurb: "Hygiène et soins dentaires", category: "Bucco-Dentaire", image: null },
  { blurb: "Vitamines, minéraux et bien-être", category: "Compléments alimentaires", image: SHOT("complements.png") },
  { blurb: "Les essentiels du quotidien", category: "Hygiène", image: SHOT("arbre-hiver.png") },
];
